import React from "react";
import { AiWarningBadge } from "aihappey-components";

export default {
  title: "Badges/AiWarningBadge",
  component: AiWarningBadge,
};

export const Default = () =>
  React.createElement(AiWarningBadge);

export const WithLabel = () =>
  React.createElement(AiWarningBadge, {
    label: "Generated by AI",
  });

export const Small = () =>
  React.createElement(AiWarningBadge, {
    label: "AI",
    size: "small",
  });

export const Large = () =>
  React.createElement(AiWarningBadge, {
    label: "AI Generated Content",
    size: "large",
  });
