import anthropicPricing from "./pricing/anthropic.json";
import zaiPricing from "./pricing/zai.json";

// This file is generated by scripts/generate-provider-pricing-index.cjs.
// Add a provider pricing JSON file under ./pricing and run the package build to update it.
export const PROVIDER_PRICING_CATALOGS = {
  "anthropic": anthropicPricing,
  "zai": zaiPricing,
} as const;
