/** English-only documentation content. Keep reusable API and page copy here. */
export const docsContent = {
      language: {
        selectorLabel: "Language",
      },
      header: {
        searchPlaceholder: "Search docs",
        dashboard: "Dashboard ↗",
      },
      api: {
        sections: {
          overview: "Overview",
          authentication: "Authentication",
          parameters: "Parameters",
          requestBody: "Request body",
          requestExamples: "Request examples",
          responses: "Responses",
          errors: "Errors",
          related: "Related",
        },
        table: {
          name: "Name",
          type: "Type",
          required: "Required",
          description: "Description",
          optional: "Optional",
        },
        responseCard: {
          title: "Response",
        },
        test: {
          reset: "Reset",
          close: "Close",
          sendRequest: "Send request",
          sending: "Sending…",
          responseType: "Response: {{responseType}}",
          endpoint: "Endpoint",
          method: "Method",
          url: "URL",
          headers: "Headers",
          addHeader: "Add header",
          name: "Name",
          value: "Value",
          headerNamePlaceholder: "Header name",
          headerValuePlaceholder: "Header value",
          remove: "Remove",
          body: "Body",
          formatJson: "Format JSON",
          noRequestBody: "This method does not send a request body.",
          requestBody: "Request body",
          formData: "Form data",
          response: "Response",
          downloadAudio: "Download audio",
          downloadResponseFile: "Download response file",
          responseBody: "Response body",
          responseHeaders: "Response headers",
          emptyResponse: "<empty response>",
          noResponseHeaders: "<no response headers>",
          invalidJsonBody: "Request body is not valid JSON.",
          missingUrl: "Enter an endpoint URL before sending the request.",
          invalidRequestBodyJson: "Request body JSON is invalid: {{message}}",
          invalidRequestBodyJsonFallback: "Request body JSON is invalid.",
          requestFailed: "The request failed before a response was returned.",
          missingRequiredField: "Enter a value for required field {{name}}.",
          missingRequiredFile: "Choose a file for required field {{name}}.",
          receivedBlob: "Received {{size}} ({{type}}).",
          receivedBinary: "Received {{size}} binary response.",
        },
      },
      gateway: {
        common: {
          auth: "Send a bearer token with every request.",
          relatedGatewayOverview: "Gateway overview",
        },
      },
      agents: {
        common: {
          auth: "The HeaderAuth host forwards editable X-* headers to the downstream AI backend. A package consumer can instead provide getAccessToken to inject an Entra bearer token into every live documentation request.",
          relatedOverview: "Agent API overview",
          errors: { unauthorized: "The deployment requires authentication and the request did not contain valid credentials." },
        },
        overview: {
          title: "Agent API Overview",
          summary: "Run single agents and multi-agent workflows through OpenAI-compatible Responses endpoints or the AI SDK UI message stream.",
          startTitle: "Start here",
          start: "List the available agent models, then select an agent model for a Responses request or provide complete agent definitions to the AI SDK chat route. The runtime orchestrates agents and forwards model calls to its configured AI backend.",
          authTitle: "Authentication and downstream headers",
          auth: "Authentication is selected by the hosting application. The HeaderAuth sample accepts requests directly and forwards inbound X-* headers, including provider keys. The AzureAuth sample validates Entra ID bearer tokens and acquires a downstream token. Docs package consumers can configure static headers, getAccessToken, and a custom fetch implementation once on DocsRoot; those settings apply to every live Test dialog.",
          executionTitle: "Agents and workflows",
          execution: "A single resolved agent runs directly. Multiple agents can execute sequential, concurrent, group-chat, or handoff workflows. Requests may select catalog models, submit agent definitions, and include workflow metadata or a workflow file.",
          responsesTitle: "Streaming and background responses",
          responses: "Responses can return completed JSON or OpenAI-compatible server-sent events. Non-streaming requests can use background mode when asynchronous response storage is configured, then use retrieve and delete operations with the returned response ID. AI SDK chat always emits a UI message stream.",
        },
        endpoints: {
          models: { title: "List agent models", surface: "OpenAI compatible", summary: "List agents exposed as OpenAI-compatible models.", description: "Returns the runtime model catalog. Agent-backed entries include the complete agent definition used for execution.", testLabel: "Test", testModalTitle: "Test agent models", testDescription: "Add any X-* downstream provider headers required by the HeaderAuth deployment, then retrieve the catalog.", parameters: { forwardedHeaders: "Optional host-specific header forwarded to downstream services. The catalog itself may not require a provider key." }, responses: { success: "An OpenAI-compatible model list containing agent model metadata and definitions." } },
          createResponse: { title: "Create response", surface: "OpenAI compatible", summary: "Run an agent or workflow with the Responses API.", description: "Accepts OpenAI Responses input, resolves one or more agents, and returns completed JSON or an SSE stream. Background mode queues non-streaming work when asynchronous storage is configured.", testLabel: "Test", testModalTitle: "Test create response", testDescription: "Choose a catalog agent model and edit the input. Add X-* provider headers when required by the downstream AI backend.", parameters: { input: "Required Responses API input as text or supported conversation items.", model: "A catalog agent model ID. Required unless models or metadata.agents selects execution targets.", models: "Optional list of catalog agent model IDs for a workflow.", agents: "Optional inline agent definitions supplied through metadata.agents.", stream: "Set true for OpenAI-compatible server-sent response events.", background: "Queue a non-streaming response. Cannot be combined with stream and requires configured async storage." }, responses: { success: "A completed response, a queued response when background is true, or response events when stream is true." }, errors: { badRequest: "Input is missing, no supported conversation items were found, no execution target was supplied, or background and streaming were combined.", server: "Agent preparation, workflow execution, downstream generation, or background queueing failed." }, relatedRetrieve: "Retrieve response" },
          retrieveResponse: { title: "Retrieve response", surface: "OpenAI compatible", summary: "Retrieve a stored background response by ID.", description: "Reads the latest stored state for a response created with background mode. Availability depends on configured asynchronous response storage.", testLabel: "Test", testModalTitle: "Test retrieve response", testDescription: "Replace the response ID in the editable URL with the ID returned by a background create request.", parameters: { responseId: "Response identifier returned by a background create request." }, responses: { success: "The queued, in-progress, completed, or failed stored response." }, errors: { badRequest: "The response ID path value is empty.", notFound: "No stored response exists for this identifier." } },
          deleteResponse: { title: "Delete response", surface: "OpenAI compatible", summary: "Delete a stored background response by ID.", description: "Removes a response from asynchronous storage and returns an OpenAI-compatible deletion acknowledgement.", testLabel: "Test", testModalTitle: "Test delete response", testDescription: "Replace the response ID in the editable URL. Deletion is permanent for the configured response store.", parameters: { responseId: "Stored response identifier to delete." }, responses: { success: "A deletion acknowledgement containing id, object, and deleted: true." }, errors: { badRequest: "The response ID path value is empty.", notFound: "No stored response exists for this identifier." } },
          listResponses: { title: "List responses", surface: "OpenAI compatible", summary: "List responses exposed by the current runtime implementation.", description: "Returns an OpenAI-compatible list envelope. The reference backend currently returns an empty data array; use retrieve with a known background response ID to read stored work.", testLabel: "Test", testModalTitle: "Test list responses", testDescription: "Send the request to inspect the list envelope implemented by the current host.", responses: { success: "A list object. In the reference backend, data is currently always empty." } },
          chat: { title: "Chat", surface: "AI SDK", summary: "Execute agents and workflows as an AI SDK UI message stream.", description: "Sends UI messages and agent execution settings to the runtime. The endpoint always streams typed AI SDK UI message parts and reports runtime failures as stream parts after streaming begins.", testLabel: "Test", testModalTitle: "Test agent AI SDK chat", testDescription: "Edit the inline agent, workflow, and UI messages. The live result is displayed as the raw server-sent event stream.", parameters: { id: "Client request or conversation identifier.", messages: "AI SDK UI messages with typed parts.", agents: "Optional inline agent definitions, including model, instructions, tools, skills, and MCP servers.", model: "Optional catalog agent model identifier.", models: "Optional catalog model identifiers for multi-agent execution.", workflowType: "Workflow strategy: sequential, concurrent, groupchat, or handoff.", workflowFile: "Optional encoded workflow definition supported by the runtime.", workflowMetadata: "Optional group-chat, handoff, or magentic workflow controls." }, responses: { success: "An AI SDK UI message stream containing start, text, reasoning, tool, file, workflow, finish, or error parts." }, errors: { badRequest: "The message, agent, model, or workflow payload cannot be prepared.", server: "Agent execution or downstream generation failed; after streaming begins the failure is emitted as an error part." } },
        },
      },
      models: {
        openai: {
          title: "List models",
          surface: "OpenAI compatible",
          summary: "List models available through provider-keyed gateway authentication.",
          descriptionPrefix: "List OpenAI-compatible model ids available for the provider API keys sent with the request. For this route, send provider-key headers such as",
          descriptionMiddle: "instead of",
          descriptionSuffix: ".",
          authPrefix: "This endpoint does not support bearer authentication. Send one or more provider-key headers such as",
          authMiddle: ". Do not use",
          authSuffix: "for /v1/models.",
          testLabel: "Test",
          testModalTitle: "Test OpenAI-compatible models",
          testDescription: "Enter an OpenAI provider API key in X-OpenAI-Key, or replace the header with another supported provider-key header. Do not send Authorization bearer credentials to this endpoint.",
          relatedChat: "OpenAI-compatible chat completions",
          parameters: {
            xOpenAIKey: "OpenAI provider API key used to include OpenAI-backed models in the result.",
            xAnthropicKey: "Anthropic provider API key used to include Anthropic-backed models in the result.",
            xGoogleKey: "Google provider API key used to include Google-backed models in the result.",
            providerKey: "Any supported provider API key header. The gateway lists models for providers with keys present on the request.",
          },
          responses: {
            json: "A model list response containing provider-qualified model identifiers plus metadata fields: id, object, created, owned_by, name, description, context_window, max_tokens, type, tags, and pricing. Tags can include predefined values such as agent for agent models, translate for translation models, and voice for text-to-speech voice shortcut models. Locale hints can appear in text fields using two-letter or xx-XX notation.",
          },
          errors: {
            unauthorized: "No supported provider-key header was supplied, or the supplied provider API key was rejected.",
            providerFailed: "The gateway could not resolve model metadata from the configured providers.",
          },
        },
      },
      chat: {
        openai: {
          title: "Create chat completion",
          surface: "OpenAI compatible",
          summary: "Create chat completions using the OpenAI-compatible chat endpoint.",
          descriptionPrefix: "Create a chat completion through the OpenAI-compatible route. The gateway accepts",
          descriptionMiddle: "with a provider-qualified model id, forwards tools and extra compatible properties, and emits server-sent event chunks when",
          descriptionSuffix: "is true.",
          testLabel: "Test",
          testModalTitle: "Test OpenAI-compatible chat completions",
          testDescription: "Edit the bearer token, model, and messages, then send a live chat completion request. JSON responses are formatted automatically.",
          relatedResponses: "OpenAI-compatible responses",
          parameters: {
            model: "Chat-capable model or provider-qualified model identifier.",
            messages: "Conversation messages in OpenAI chat format.",
            messageRole: "Message role such as system, developer, user, assistant, or tool.",
            messageContent: "Message content as text or provider-supported structured content parts.",
            stream: "Set to true to receive chat.completion.chunk server-sent events and a final [DONE] marker.",
            temperature: "Optional sampling temperature when supported by the selected model.",
            tools: "Optional OpenAI-compatible tool definitions.",
            toolChoice: "Optional tool choice policy.",
            responseFormat: "Optional response format request, for example JSON object or JSON schema mode when supported.",
            reasoningEffort: "Optional reasoning effort for reasoning-capable models.",
            metadata: "Optional metadata key-value pairs for tracing or downstream provider support.",
          },
          responses: {
            json: "A completed chat.completion object is returned when stream is omitted or false.",
            sse: "When stream is true, chat completion chunks are emitted as server-sent events and terminated with [DONE].",
          },
          errors: {
            badRequest: "The request is missing messages or model, selects an unavailable model, or contains an invalid chat payload.",
            unauthorized: "The request did not include a valid bearer token.",
            providerFailed: "The provider failed while creating the chat completion.",
          },
        },
        aiSdk: {
          title: "Chat",
          surface: "AI SDK",
          summary: "Stream AI SDK UI messages through the gateway chat endpoint.",
          description: "Send AI SDK UI messages, tools, generation settings, and provider metadata to a provider-qualified model. This endpoint always returns the AI SDK UI message stream protocol as server-sent events and sets x-vercel-ai-ui-message-stream to v1.",
          testLabel: "Test",
          testModalTitle: "Test AI SDK chat",
          testDescription: "Edit the bearer token, model, and UI messages, then send a live request. The modal displays the server-sent event stream as text.",
          relatedOpenAiChat: "OpenAI-compatible chat completions",
          relatedMessages: "Anthropic-compatible messages",
          parameters: {
            model: "Chat-capable provider-qualified model identifier.",
            messages: "AI SDK UI messages containing roles and typed parts.",
            parts: "Typed UI message parts, such as text, file, reasoning, or tool invocation parts.",
            tools: "Optional AI SDK tool definitions. Duplicate tool names are removed by the gateway.",
            toolChoice: "Optional tool selection policy.",
            maxToolCalls: "Optional maximum number of tool calls for the request.",
            temperature: "Sampling temperature. The default is 1.",
            topP: "Optional nucleus sampling value.",
            maxOutputTokens: "Optional maximum number of generated output tokens.",
            providerMetadata: "Optional provider-specific metadata and generation options.",
          },
          responses: { sse: "An AI SDK UI message stream containing typed data parts is returned as server-sent events." },
          errors: {
            badRequest: "The model or UI message payload is invalid, or the selected model is unavailable.",
            unauthorized: "The request did not include a valid bearer token.",
            streamError: "Errors after streaming starts are emitted as AI SDK error parts in the successful SSE response.",
          },
        },
      },
      messages: {
        anthropic: {
          title: "Create message",
          surface: "Anthropic compatible",
          summary: "Create or stream a message using the Anthropic-compatible Messages API.",
          description: "Send Anthropic Messages API payloads through the gateway with a provider-qualified model. The route supports text or structured content, system prompts, tools, thinking options, provider passthrough headers, and server-sent event streaming.",
          testLabel: "Test",
          testModalTitle: "Test Anthropic-compatible messages",
          testDescription: "Edit the bearer token, model, maximum token count, and messages, then send a non-streaming live request. The anthropic-version compatibility header is included.",
          relatedAiChat: "AI SDK chat",
          relatedOpenAiChat: "OpenAI-compatible chat completions",
          parameters: {
            model: "Messages-capable provider-qualified model identifier.",
            maxTokens: "Optional maximum number of output tokens. Provider requirements still apply.",
            messages: "Conversation messages with user or assistant roles and text or structured content blocks.",
            system: "Optional system prompt as text or structured content blocks.",
            stream: "Set to true to receive Anthropic-compatible message events followed by [DONE].",
            temperature: "Optional sampling temperature.",
            tools: "Optional Anthropic-compatible tool definitions.",
            toolChoice: "Optional tool choice configuration.",
            thinking: "Optional extended-thinking configuration for supported models.",
            metadata: "Optional request metadata, including supported user identifiers.",
          },
          responses: {
            json: "A completed Anthropic-compatible message object is returned when stream is omitted or false.",
            sse: "When stream is true, message events are returned as server-sent events and terminated with [DONE].",
          },
          errors: {
            badRequest: "The model is missing or unavailable, or the Messages API payload is invalid.",
            unauthorized: "The request did not include a valid bearer token.",
            providerFailed: "The selected provider failed while creating the message.",
          },
        },
      },
      images: {
        openai: {
          surface: "OpenAI compatible",
          common: {
            parameters: {
              n: "Optional number of images to generate or return.",
              size: "Optional output size such as 1024x1024, 1024x1536, or a provider-specific size.",
              quality: "Optional image quality such as standard, hd, high, medium, or provider-specific values.",
              background: "Optional background handling such as auto, transparent, or opaque when supported.",
              outputFormat: "Optional output format such as png, jpeg, or webp when supported.",
              outputCompression: "Optional output compression percentage when supported.",
              responseFormat: "Optional response format. url requests URL output when the provider returns URLs; b64_json is the normalized default.",
              partialImages: "Optional number of partial images to emit during streaming when supported.",
              user: "Optional end-user identifier forwarded for provider abuse monitoring or tracing.",
            },
            errors: {
              unauthorized: "The request did not include a valid bearer token.",
              providerFailed: "The provider failed while processing the image request. Streaming requests receive an error event instead.",
            },
          },
          generation: {
            title: "Create image",
            summary: "Generate images from prompts using the OpenAI-compatible image generation endpoint.",
            descriptionPrefix: "Create images through the OpenAI-compatible route. The gateway accepts",
            descriptionMiddle: "with image options, resolves the provider-qualified model, and can emit image generation events when",
            descriptionSuffix: "is true.",
            testLabel: "Test",
            testModalTitle: "Test OpenAI-compatible image generation",
            testDescription: "Edit the bearer token, model, prompt, and image options, then send a live generation request. JSON responses are formatted automatically.",
            relatedEdit: "OpenAI-compatible image edits",
            parameters: {
              prompt: "Text prompt describing the image to generate.",
              model: "Image-generation-capable model or provider-qualified model identifier.",
              stream: "Set to true to receive image_generation.partial_image and image_generation.completed server-sent events when supported.",
              style: "Optional style hint when supported by the selected model.",
            },
            responses: {
              json: "A generated image response is returned with data[].b64_json by default or data[].url when URL output is available and requested.",
              sse: "Streaming generation requests emit image_generation events with base64 image payloads.",
            },
            errors: {
              badRequest: "The request is missing prompt, uses invalid image counts or partial image options, or selects an unavailable model.",
            },
          },
          edit: {
            title: "Edit image",
            summary: "Edit existing images using JSON image references or multipart uploads.",
            descriptionPrefix: "Edit images through the OpenAI-compatible route. The gateway accepts",
            descriptionMiddle: "as JSON references or multipart files, applies the prompt, and can emit image edit events when",
            descriptionSuffix: "is true.",
            testLabel: "Test",
            testModalTitle: "Test OpenAI-compatible image edits",
            testDescription: "Edit the bearer token, model, prompt, and choose one or more local image files, then send a live multipart edit request.",
            relatedVariation: "OpenAI-compatible image variations",
            parameters: {
              prompt: "Text instruction describing how to edit the supplied image or images.",
              images: "JSON image references. Each entry can include image_url.",
              imageFile: "Multipart image file field for upload-based edits. Repeat the image field for multiple files when supported by the client.",
              mask: "Optional mask as a JSON image reference or multipart mask file.",
              model: "Image-edit-capable model or provider-qualified model identifier.",
              inputFidelity: "Optional fidelity control for preserving input details when supported.",
              stream: "Set to true to receive image_edit.partial_image and image_edit.completed server-sent events when supported.",
            },
            responses: {
              json: "An edited image response is returned with data[].b64_json by default.",
              sse: "Streaming edit requests emit image_edit events with base64 image payloads.",
            },
            errors: {
              badRequest: "The request is missing prompt or image input, uses invalid image counts, or selects an unavailable model.",
            },
          },
          variation: {
            title: "Create image variation",
            summary: "Create image variations from a source image using the OpenAI-compatible endpoint.",
            descriptionPrefix: "Create image variations through the OpenAI-compatible route. The gateway accepts",
            descriptionMiddle: "as a JSON reference or multipart file and returns generated variants. This endpoint does not expose",
            descriptionSuffix: "streaming in the current controller.",
            testLabel: "Test",
            testModalTitle: "Test OpenAI-compatible image variations",
            testDescription: "Edit the bearer token, model, and choose a local image file, then send a live multipart variation request.",
            relatedGeneration: "OpenAI-compatible image generation",
            parameters: {
              image: "Source image as a JSON reference with image_url, or as a multipart image file.",
              model: "Image-variation-capable model or provider-qualified model identifier.",
            },
            responses: {
              json: "An image variation response is returned with generated image data.",
            },
            errors: {
              badRequest: "The request is missing image input, uses invalid image counts, or selects an unavailable model.",
            },
          },
        },
        aiSdk: {
          title: "Create images", surface: "AI SDK", summary: "Generate or edit images using the AI SDK gateway image endpoint.", description: "Send a provider-qualified image model, prompt, optional source files or mask, and generation settings. The gateway returns AI SDK-style image data, warnings, usage, response metadata, and provider metadata.",
          testLabel: "Test", testModalTitle: "Test AI SDK images", testDescription: "Edit the bearer token, model, prompt, and image options, then send a live JSON request.", relatedOpenAi: "OpenAI-compatible image generation", relatedUi: "AI SDK UI",
          parameters: { model: "Image-capable provider-qualified model identifier.", prompt: "Text description of the image or edit to produce.", size: "Optional output size such as 1024x1024.", aspectRatio: "Optional output aspect ratio when supported.", seed: "Optional deterministic generation seed.", n: "Optional number of images to generate.", files: "Optional source images, each with type, mediaType, and base64 data.", mask: "Optional mask file with type, mediaType, and base64 data.", providerOptions: "Optional provider-specific image settings." },
          responses: { json: "Generated images as data URLs with warnings, usage, response metadata, and provider metadata." }, errors: { badRequest: "The model, prompt, files, mask, or image options are invalid.", unauthorized: "The request did not include a valid bearer token." },
        },
      },
      speech: {
        common: {
          auth: "Send a bearer token with every request.",
          relatedGatewayOverview: "Gateway overview",
        },
        openai: {
          title: "Create speech",
          surface: "OpenAI compatible",
          summary: "Generate speech audio from text using the OpenAI-compatible audio speech endpoint.",
          descriptionPrefix: "Create speech audio through the OpenAI-compatible audio endpoint. This route accepts the OpenAI text-to-speech request shape and returns raw audio bytes by default, or server-sent events when",
          descriptionMiddle: "is set to",
          descriptionSuffix: ".",
          testLabel: "Test",
          testModalTitle: "Test OpenAI-compatible speech",
          testDescription: "Edit the bearer token, model, voice, and input, then send a live request. Audio responses can be played directly in the modal or downloaded.",
          relatedAiSdkSpeech: "AI SDK speech",
          parameters: {
            model: "Speech-capable model or provider-qualified model identifier.",
            input: "Text to synthesize into audio.",
            voice: "Voice identifier supported by the selected model or provider.",
            response_format: "Optional output format such as mp3, wav, opus, flac, aac, or pcm when supported by the provider.",
            instructions: "Optional provider instructions for tone, delivery, or speaking style.",
            speed: "Optional speech speed multiplier when supported by the provider.",
            stream_format: "Set to sse to receive speech.audio.delta and speech.audio.done events instead of a binary audio response.",
          },
          responses: {
            binary: "Binary audio is returned by default with the generated file content in the response body.",
            sse: "When stream_format is sse, the endpoint emits OpenAI-style speech audio events and terminates with [DONE].",
          },
          errors: {
            badRequest: "The request body is missing input, model, or voice, or the selected model is not available.",
            unauthorized: "The request did not include a valid bearer token.",
            providerFailed: "The provider failed while generating speech audio. SSE requests receive an error event instead.",
          },
        },
        aiSdk: {
          title: "Create speech",
          surface: "AI SDK",
          summary: "Generate speech audio from text using the AI SDK gateway speech endpoint.",
          description: "Generate speech audio through the AI SDK gateway route. This route uses the Vercel AI SDK speech request shape and returns JSON metadata with the generated audio encoded as base64.",
          testLabel: "Test",
          testModalTitle: "Test AI SDK speech",
          testDescription: "Edit the bearer token and JSON body, then send a live request. JSON responses are formatted automatically, and binary audio responses can still be downloaded.",
          relatedOpenAiSpeech: "OpenAI-compatible speech",
          parameters: {
            model: "Speech-capable model or provider-qualified model identifier.",
            text: "Text to synthesize into audio.",
            voice: "Voice identifier supported by the selected model or provider. Some providers require this value.",
            outputFormat: "Optional output format such as mp3, wav, opus, flac, aac, or pcm when supported by the provider.",
            instructions: "Optional provider instructions for tone, delivery, or speaking style.",
            speed: "Optional speech speed multiplier when supported by the provider.",
            language: "Optional language hint for providers that support explicit speech language selection.",
            providerOptions: "Provider-specific options keyed by provider identifier, for example openai, deepgram, elevenlabs, minimax, or together.",
          },
          responses: {
            json: "Speech request accepted and JSON metadata is returned with the generated audio encoded in audio.base64.",
          },
          errors: {
            badRequest: "The selected model is not available or the provider rejects the request payload.",
            unauthorized: "The request did not include a valid bearer token.",
            rateLimited: "The selected provider or model deployment is currently rate limited.",
          },
        },
      },
      embeddings: {
        openai: {
          title: "Create embeddings", surface: "OpenAI compatible",
          summary: "Create vector embeddings using the OpenAI-compatible embeddings endpoint.",
          description: "Submit one string or an array of strings to a provider-qualified embedding model. The response follows the OpenAI list shape and supports float vectors or provider-supported base64 encoding.",
          testLabel: "Test", testModalTitle: "Test OpenAI-compatible embeddings", testDescription: "Edit the bearer token, model, input, and encoding format, then send a live embedding request.",
          relatedAiSdk: "AI SDK embeddings",
          parameters: {
            model: "Embedding-capable model or provider-qualified model identifier.",
            input: "Text, token array, or array of text or token arrays to embed.",
            dimensions: "Optional number of dimensions in the output vectors when supported by the model.",
            encodingFormat: "Output encoding: float for numeric arrays or base64 when supported by the provider.",
            user: "Optional end-user identifier forwarded to providers that support it.",
          },
          responses: { json: "An OpenAI-compatible list containing ordered embedding vectors, model information, and token usage." },
          errors: {
            badRequest: "The model is unavailable, the input is invalid, or the provider does not support the requested embedding options.",
            unauthorized: "The request did not include a valid bearer token.",
            providerFailed: "The provider failed while creating embeddings.",
          },
        },
        aiSdk: {
          title: "Create embeddings", surface: "AI SDK",
          summary: "Embed multiple text values using the AI SDK gateway embeddings endpoint.",
          description: "Submit an ordered list of text values using the Vercel AI SDK EmbeddingModelV4 wire shape. The gateway returns vectors in the same order with usage, warnings, response metadata, and provider metadata.",
          testLabel: "Test", testModalTitle: "Test AI SDK embeddings", testDescription: "Edit the bearer token, model, values, and provider options, then send a live embedding request.",
          relatedOpenAi: "OpenAI-compatible embeddings",
          parameters: {
            model: "Embedding-capable model or provider-qualified model identifier.",
            values: "Ordered array of strings to embed.",
            providerOptions: "Provider-specific embedding options keyed by provider identifier.",
          },
          responses: { json: "Ordered embedding vectors with token usage, warnings, response metadata, and provider metadata." },
          errors: {
            badRequest: "The model is unavailable, required values are missing, or the provider rejects the embedding payload.",
            unauthorized: "The request did not include a valid bearer token.",
            providerFailed: "The selected provider or model deployment is currently rate limited.",
          },
        },
      },
      transcriptions: {
        openai: {
          title: "Create transcription",
          surface: "OpenAI compatible",
          summary: "Transcribe audio files using the OpenAI-compatible audio transcriptions endpoint.",
          descriptionPrefix: "Create audio transcriptions through the OpenAI-compatible endpoint. This route accepts",
          descriptionMiddle: "with an audio file, bridges supported OpenAI fields to the gateway provider contract, and can emit text delta events when",
          descriptionSuffix: "is true.",
          relatedAiSdkTranscriptions: "AI SDK transcriptions",
          parameters: {
            file: "Audio file to transcribe. Send this as a multipart form file field.",
            model: "Transcription-capable model or provider-qualified model identifier.",
            language: "Optional language hint for providers that support explicit input language selection.",
            prompt: "Optional prompt or context to guide transcription when supported by the provider.",
            response_format: "Optional response format. json is the default; text returns plain text; verbose_json includes language, duration, and segments when available.",
            temperature: "Optional sampling temperature for providers that support transcription temperature.",
            timestamp_granularities: "Optional timestamp granularity hints for providers that support segment or word timing.",
            stream: "Set to true to receive transcript.text.delta and transcript.text.done server-sent events instead of a regular response body.",
            include: "Optional extra fields. Unsupported include options are rejected by the compatibility layer.",
          },
          responses: {
            json: "Default JSON responses return the transcribed text.",
            verbose: "Verbose JSON responses include the transcribed text plus language, duration, and segments when the provider returns them.",
            sse: "Streaming requests emit transcription text events and terminate with [DONE].",
          },
          errors: {
            badRequest: "The request is missing a file or model, uses an unsupported response format, or selects an unavailable model.",
            unauthorized: "The request did not include a valid bearer token.",
            providerFailed: "The provider failed while transcribing audio. Streaming requests receive an error event instead.",
          },
        },
        aiSdk: {
          title: "Create transcription",
          surface: "AI SDK",
          summary: "Transcribe base64 audio using the AI SDK gateway transcription endpoint.",
          descriptionPrefix: "Create transcriptions through the AI SDK gateway route. This route uses the Vercel AI SDK transcription request shape with",
          descriptionMiddle: "as a data URL or raw base64 string and",
          descriptionSuffix: " as the audio MIME type.",
          testLabel: "Test",
          testModalTitle: "Test AI SDK transcription",
          testDescription: "Edit the bearer token, model, audio data URL, and media type, then send a live transcription request. JSON responses are formatted automatically.",
          relatedOpenAiTranscriptions: "OpenAI-compatible transcriptions",
          parameters: {
            model: "Transcription-capable model or provider-qualified model identifier.",
            audio: "Audio input as a data URL or raw base64 string.",
            mediaType: "Audio MIME type matching the provided audio payload, for example audio/mpeg, audio/wav, or audio/webm.",
            providerOptions: "Provider-specific options keyed by provider identifier, for example openai, deepgram, assemblyai, or cohere.",
          },
          responses: {
            json: "Transcription request accepted and JSON metadata is returned with text, warnings, response metadata, and optional language, duration, or segments.",
          },
          errors: {
            badRequest: "The selected model is not available, required request fields are missing, or the provider rejects the transcription payload.",
            unauthorized: "The request did not include a valid bearer token.",
            rateLimited: "The selected provider or model deployment is currently rate limited.",
          },
        },
        streaming: {
          title: "Stream transcription", surface: "AI SDK",
          summary: "Stream structured transcription parts from complete base64-encoded audio.",
          description: "Send a complete audio file as plain base64 with its input format. The gateway emits Vercel AI SDK transcription parts as server-sent events, including start, metadata, delta, partial, final, finish, raw, and error parts, followed by [DONE].",
          testLabel: "Test", testModalTitle: "Test AI SDK streaming transcription", testDescription: "Replace the sample audio with complete plain base64 audio, edit the model and format, then inspect the live SSE response.",
          relatedTranscriptions: "AI SDK transcriptions",
          parameters: {
            model: "Streaming-transcription-capable model or provider-qualified model identifier.",
            audio: "Complete audio file encoded as plain base64 without a data URL prefix.",
            inputAudioFormat: "Audio format descriptor containing the required type and optional sample rate.",
            type: "Input audio format such as mp3, wav, webm, ogg, flac, or pcm.",
            rate: "Optional sample rate in hertz, primarily used for raw PCM audio.",
            providerOptions: "Provider-specific streaming transcription options keyed by provider identifier.",
            includeRawChunks: "When true, include provider raw chunks as raw stream parts when available.",
          },
          responses: { sse: "A text/event-stream response containing typed transcription parts and a final data: [DONE] marker." },
          errors: {
            badRequest: "The model is unavailable or required audio and format fields are missing or invalid.",
            unauthorized: "The request did not include a valid bearer token.",
            streamError: "After streaming starts, provider failures are emitted as a typed error part in the SSE stream.",
          },
        },
      },
      responses: {
        openai: {
          title: "Create response",
          surface: "OpenAI compatible",
          summary: "Create model responses with the OpenAI-compatible Responses API endpoint.",
          descriptionPrefix: "Create responses through the OpenAI-compatible endpoint. The gateway accepts the Responses API request shape with",
          descriptionMiddle: "as a string or structured message array, forwards compatible tools and options, and emits server-sent events when",
          descriptionSuffix: "is true.",
          testLabel: "Test",
          testModalTitle: "Test OpenAI-compatible responses",
          testDescription: "Edit the bearer token, model, and input, then send a live response request. JSON responses are formatted automatically.",
          relatedRealtime: "OpenAI-compatible realtime",
          parameters: {
            model: "Response-capable model or provider-qualified model identifier.",
            input: "User input as a string or an array of Responses API input items.",
            instructions: "Optional system or developer instructions applied to the response.",
            stream: "Set to true to receive Responses API server-sent events and a final [DONE] marker.",
            temperature: "Optional sampling temperature when supported by the selected model.",
            top_p: "Optional nucleus sampling value when supported by the selected model.",
            max_output_tokens: "Optional maximum number of output tokens to generate.",
            tools: "Optional Responses API tool definitions such as function tools or provider-supported built-in tools.",
            tool_choice: "Optional tool choice policy as a string or object.",
            reasoning: "Optional reasoning configuration for reasoning-capable models.",
            metadata: "Optional metadata key-value pairs for tracing or downstream provider support.",
          },
          responses: {
            json: "A completed response object is returned when stream is omitted or false.",
            sse: "When stream is true, response events are emitted as server-sent events and terminated with [DONE].",
          },
          errors: {
            badRequest: "The request is missing input or model, selects an unavailable model, or contains an invalid Responses API payload.",
            unauthorized: "The request did not include a valid bearer token.",
            providerFailed: "The provider failed while creating the response. Streaming requests receive an error event instead.",
          },
        },
      },
      realtime: {
        openai: {
          title: "Create realtime client secret",
          surface: "OpenAI compatible",
          summary: "Create a short-lived realtime client secret or provider token for browser and voice sessions.",
          descriptionPrefix: "Create a realtime token through",
          descriptionMiddle: ". The gateway resolves the provider-qualified model, forwards optional",
          descriptionSuffix: ", and returns the token value, expiry, and provider metadata.",
          testLabel: "Test",
          testModalTitle: "Test OpenAI-compatible realtime token",
          testDescription: "Edit the bearer token and model, then request a short-lived realtime client secret. JSON responses are formatted automatically.",
          relatedResponses: "OpenAI-compatible responses",
          parameters: {
            model: "Realtime-capable model or provider-qualified model identifier.",
            providerOptions: "Provider-specific realtime session options keyed by provider identifier, for example openai, deepgram, assemblyai, elevenlabs, or gladia.",
          },
          responses: {
            json: "A realtime client secret or provider token is returned with an expiry timestamp and optional provider metadata.",
          },
          errors: {
            badRequest: "The selected model is not available or the provider rejects the realtime token request.",
            unauthorized: "The request did not include a valid bearer token.",
            providerFailed: "The provider failed while creating the realtime token.",
          },
        },
      },
      rerank: {
        aiSdk: {
          title: "Rerank documents",
          surface: "AI SDK",
          summary: "Score and reorder documents for a query using the AI SDK gateway reranking endpoint.",
          description: "Use the AI SDK reranking route to submit a query and a typed document collection. The gateway resolves the provider-qualified model, forwards the reranking request, and returns ranked indexes with relevance scores, warnings, response metadata, and provider metadata.",
          testLabel: "Test",
          testModalTitle: "Test AI SDK rerank",
          testDescription: "Edit the bearer token, model, query, documents, and topN value, then send a live reranking request. JSON responses are formatted automatically.",
          relatedVideo: "AI SDK video",
          parameters: {
            model: "Reranking-capable model or provider-qualified model identifier.",
            query: "Search query or user intent used to rank the provided documents.",
            documents: "Typed document container. Use type and values to describe the document payload sent to the provider.",
            documentsType: "Document value type. Text reranking uses text.",
            documentsValues: "Documents to rerank. For text reranking this is an array of strings in their original order.",
            topN: "Optional maximum number of ranked results to return.",
            providerOptions: "Provider-specific options keyed by provider identifier, for example cohere or voyage.",
          },
          responses: {
            json: "Reranking request accepted and JSON metadata is returned with ranking entries sorted by relevance.",
          },
          errors: {
            badRequest: "The selected model is not available, required request fields are missing, or the provider rejects the reranking payload.",
            unauthorized: "The request did not include a valid bearer token.",
            rateLimited: "The selected provider or model deployment is currently rate limited.",
          },
        },
      },
      ui: {
        aiSdk: {
          title: "UI", surface: "AI SDK", summary: "Stream generated user-interface markup from a model.",
          description: "Send a UI prompt, catalog instructions, optional context, and generation settings to a provider-qualified model. The gateway streams text deltas directly as a plain-text response.",
          testLabel: "Test", testModalTitle: "Test AI SDK UI", testDescription: "Edit the bearer token and UI generation request, then inspect the streamed text response.",
          relatedChat: "AI SDK chat", relatedImages: "AI SDK images",
          parameters: { model: "UI-capable provider-qualified model identifier.", prompt: "Description of the interface to generate.", catalogPrompt: "Design-system or component-catalog instructions that constrain the output.", context: "Optional structured application or page context.", temperature: "Sampling temperature. The default is 1.", maxOutputTokens: "Optional maximum number of generated tokens.", providerMetadata: "Optional provider-specific generation settings." },
          responses: { text: "A UTF-8 plain-text stream containing the generated UI markup or source." }, errors: { badRequest: "The model is unavailable or the UI request is invalid.", unauthorized: "The request did not include a valid bearer token." },
        },
      },
      skills: {
        common: {
          surface: "OpenAI compatible", testLabel: "Test",
          parameters: { skillId: "Provider-prefixed skill ID returned by the List skills endpoint, for example clawhub/example-skill.", version: "Exact skill version to download.", after: "Return items after this cursor identifier.", limit: "Maximum number of items to return.", order: "Creation-time order: asc or desc." },
          errors: { unauthorized: "The request did not include a valid bearer token.", notFound: "The skill or requested version was not found.", providerFailed: "The skill provider failed while processing the request." },
          relatedList: "List skills", relatedVersions: "List skill versions",
        },
        list: { title: "List skills", summary: "List skills available through configured gateway providers.", description: "Returns an OpenAI-style paginated list with provider-qualified skill IDs and version metadata.", testModalTitle: "Test list skills", testDescription: "Edit authentication and pagination query parameters, then request the skill catalog.", responses: { success: "A paginated list of normalized skill objects." } },
        download: { title: "Download skill", summary: "Download the current content bundle for a skill.", description: "Use a skill ID returned by List skills to download its current content as a ZIP archive.", testModalTitle: "Test download skill", testDescription: "Replace the example with a skill ID returned by List skills, then download the ZIP bundle.", responses: { success: "A ZIP archive containing the skill content, including SKILL.md." } },
        versions: { title: "List skill versions", summary: "List available versions for a skill.", description: "Use a skill ID returned by List skills to retrieve an OpenAI-style paginated list of its normalized versions.", testModalTitle: "Test list skill versions", testDescription: "Replace the example with a skill ID returned by List skills and edit pagination before requesting versions.", responses: { success: "A paginated list of skill.version objects." } },
        "download-version": { title: "Download skill version", summary: "Download a specific version of a skill.", description: "Use a skill ID returned by List skills and an exact version to download that content bundle as a ZIP archive.", testModalTitle: "Test download skill version", testDescription: "Replace the example with a skill ID returned by List skills and the required version, then download the ZIP bundle.", responses: { success: "A ZIP archive containing the selected skill version." } },
      },
      video: {
        aiSdk: {
          surface: "AI SDK",
          create: {
            title: "Create video task",
            summary: "Start an asynchronous video generation task.",
            description: "Submit a prompt and optional visual inputs to a provider-qualified video model. The endpoint starts the asynchronous operation and immediately returns a provider-prefixed operation value that can be split into providerId and taskId for status polling.",
            testLabel: "Test",
            testModalTitle: "Test create video task",
            testDescription: "Edit the bearer token and request body, then start a live video task. Save the operation value from the response for the Get video task endpoint.",
            relatedGet: "Get video task",
            responses: { json: "The task was started and an operation identifier, warnings, provider metadata, and response metadata are returned." },
            errors: {
              badRequest: "The model or request payload is invalid, the model is unavailable, or the provider rejects the task.",
              notSupported: "The selected provider does not support asynchronous video generation.",
            },
          },
          get: {
            title: "Get video task",
            summary: "Retrieve the current state and result of an asynchronous video task.",
            description: "Poll a video task using the providerId and taskId extracted from the operation value returned by Create video task. The response is a discriminated status object: pending, completed with generated videos, or error with a provider message.",
            testLabel: "Test",
            testModalTitle: "Test get video task",
            testDescription: "Replace the example URL with the provider ID and URL-encoded task ID returned by Create video task, then poll the task.",
            relatedCreate: "Create video task",
            parameters: {
              providerId: "Gateway provider identifier, for example google. This selects the provider used to poll the task.",
              taskId: "Provider-local task identifier. URL-encode this path segment when it contains reserved characters.",
            },
            responses: {
              pending: "The task is still processing. Poll the same URL again after an appropriate delay.",
              completed: "The task completed and generated video data is available in videos[].",
              error: "The task reached a terminal provider error. The error field explains the failure.",
            },
            errors: {
              badRequest: "The provider ID or task ID is empty, malformed, or rejected by the provider.",
              notFound: "The provider ID is not available in this gateway.",
              notSupported: "The selected provider does not support video task polling.",
            },
          },
          parameters: {
            model: "Video-capable model or provider-qualified model identifier.",
            prompt: "Text prompt describing the video to generate.",
            resolution: "Optional output resolution such as 720p, 1080p, or a provider-specific size.",
            aspectRatio: "Optional aspect ratio such as 16:9, 9:16, or 1:1 when supported by the provider.",
            seed: "Optional seed for deterministic or reproducible generations when supported by the provider.",
            duration: "Optional video duration in seconds when supported by the provider.",
            fps: "Optional frames per second value when supported by the provider.",
            n: "Optional number of videos to generate.",
            image: "Optional base64 input image with type, mediaType, and data for image-to-video workflows.",
            inputReferences: "Optional array of input reference files for providers that support multiple visual references.",
            frameImages: "Optional first-frame or last-frame image controls. Each item includes frameType and image.",
            providerOptions: "Provider-specific options keyed by provider identifier, for example google, kling, runway, or luma.",
          },
          responses: {
            json: "Video generation accepted and JSON metadata is returned with generated files in videos[].",
          },
          errors: {
            badRequest: "The selected model is not available, required request fields are missing, or the provider rejects the video payload.",
            unauthorized: "The request did not include a valid bearer token.",
          },
        },
      },
    } as const;

type ContentValue = string | { readonly [key: string]: ContentValue };

/** Resolves an English content path without introducing locale or React context state. */
export const getDocsContent = (path: string): string => {
  const value = path.split(".").reduce<ContentValue | undefined>((current, segment) => {
    if (!current || typeof current === "string") return undefined;
    return current[segment];
  }, docsContent);

  if (typeof value !== "string") {
    throw new Error(`Unknown docs content path: ${path}`);
  }

  return value;
};
