
export const GLADIA_LANGUAGE_CODES = [
    "af",
    "am",
    "ar",
    "as",
    "az",
    "ba",
    "be",
    "bg",
    "bn",
    "bo",
    "br",
    "bs",
    "ca",
    "cs",
    "cy",
    "da",
    "de",
    "el",
    "en",
    "es",
    "et",
    "eu",
    "fa",
    "fi",
    "fo",
    "fr",
    "gl",
    "gu",
    "ha",
    "haw",
    "he",
    "hi",
    "hr",
    "ht",
    "hu",
    "hy",
    "id",
    "is",
    "it",
    "ja",
    "jw",
    "ka",
    "kk",
    "km",
    "kn",
    "ko",
    "la",
    "lb",
    "ln",
    "lo",
    "lt",
    "lv",
    "mg",
    "mi",
    "mk",
    "ml",
    "mn",
    "mr",
    "ms",
    "mt",
    "my",
    "ne",
    "nl",
    "nn",
    "no",
    "oc",
    "pa",
    "pl",
    "ps",
    "pt",
    "ro",
    "ru",
    "sa",
    "sd",
    "si",
    "sk",
    "sl",
    "sn",
    "so",
    "sq",
    "sr",
    "su",
    "sv",
    "sw",
    "ta",
    "te",
    "tg",
    "th",
    "tk",
    "tl",
    "tr",
    "tt",
    "uk",
    "ur",
    "uz",
    "vi",
    "yi",
    "yo",
    "zh",
];

export const GLADIA_TRANSLATION_TARGET_LANGUAGE_CODES = [...GLADIA_LANGUAGE_CODES, "wo"];

export const LANGUAGE_NATIVE_NAMES: Record<string, string> = {
    af: "Afrikaans",
    am: "አማርኛ",
    ar: "العربية",
    as: "অসমীয়া",
    az: "Azərbaycan",
    ba: "Башҡорт",
    be: "Беларуская",
    bg: "Български",
    bn: "বাংলা",
    bo: "བོད་ཡིག",
    br: "Brezhoneg",
    bs: "Bosanski",
    ca: "Català",
    cs: "Čeština",
    cy: "Cymraeg",
    da: "Dansk",
    de: "Deutsch",
    el: "Ελληνικά",
    en: "English",
    es: "Español",
    et: "Eesti",
    eu: "Euskara",
    fa: "فارسی",
    fi: "Suomi",
    fo: "Føroyskt",
    fr: "Français",
    gl: "Galego",
    gu: "ગુજરાતી",
    ha: "Hausa",
    haw: "ʻŌlelo Hawaiʻi",
    he: "עברית",
    hi: "हिन्दी",
    hr: "Hrvatski",
    ht: "Kreyòl ayisyen",
    hu: "Magyar",
    hy: "Հայերեն",
    id: "Bahasa Indonesia",
    is: "Íslenska",
    it: "Italiano",
    ja: "日本語",
    jw: "Basa Jawa",
    ka: "ქართული",
    kk: "Қазақ",
    km: "ខ្មែរ",
    kn: "ಕನ್ನಡ",
    ko: "한국어",
    la: "Latina",
    lb: "Lëtzebuergesch",
    ln: "Lingála",
    lo: "ລາວ",
    lt: "Lietuvių",
    lv: "Latviešu",
    mg: "Malagasy",
    mi: "Māori",
    mk: "Македонски",
    ml: "മലയാളം",
    mn: "Монгол",
    mr: "मराठी",
    ms: "Bahasa Melayu",
    mt: "Malti",
    my: "မြန်မာ",
    ne: "नेपाली",
    nl: "Nederlands",
    nn: "Nynorsk",
    no: "Norsk",
    oc: "Occitan",
    pa: "ਪੰਜਾਬੀ",
    pl: "Polski",
    ps: "پښتو",
    pt: "Português",
    ro: "Română",
    ru: "Русский",
    sa: "संस्कृतम्",
    sd: "سنڌي",
    si: "සිංහල",
    sk: "Slovenčina",
    sl: "Slovenščina",
    sn: "ChiShona",
    so: "Soomaali",
    sq: "Shqip",
    sr: "Српски",
    su: "Basa Sunda",
    sv: "Svenska",
    sw: "Kiswahili",
    ta: "தமிழ்",
    te: "తెలుగు",
    tg: "Тоҷикӣ",
    th: "ไทย",
    tk: "Türkmen",
    tl: "Tagalog",
    tr: "Türkçe",
    tt: "Татар",
    uk: "Українська",
    ur: "اردو",
    uz: "Oʻzbek",
    vi: "Tiếng Việt",
    wo: "Wolof",
    yi: "ייִדיש",
    yo: "Yorùbá",
    zh: "中文",
};
