import type { JSX } from "react";
import { IconToken } from "aihappey-types";
import { 
  Robot, 
  ChatDots, 
  ExclamationTriangle,
  Pencil,
  Trash,
  Check,
  Code,
  Globe,
  Download,
  CpuFill,
  JournalText,
  Columns,
  Calculator,
  BarChart,
  Images,
  Link,
  ThermometerHalf,
  Paperclip,
  Plugin,
  StopFill,
  CardList,
  BoxArrowUpRight,
  Shuffle,
  SignpostSplit,
  PeopleFill,
  ArrowRepeat,
  UiChecks,
  GraphUpArrow,
  ArrowUp,
  ArrowDown,
  File,
  Eye,
  Sliders,
  Search,
  List,
  Cloud,
  Server,
  DatabaseGear,
  PersonHeart,
  ChatQuote,
  Plug,
  Wrench,
  Shop,
  Mailbox,
  ArrowLeft,
  ArrowRight,
  XLg,
  Send,
  ChevronLeft,
  ChevronRight,
  ExclamationCircle,
  Chat as BSChatIcon,
  Gear,
  UsbPlug,
  UsbPlugFill,
  Printer,
  ChevronDown,
  ChevronUp,
} from "react-bootstrap-icons";

export const iconMap: Partial<Record<IconToken, JSX.Element>> = {
  robot: <Robot />,
  warning: <ExclamationTriangle />,
  add: <ChatDots />, // Default fallback or specific mapping
  edit: <Pencil />,
  delete: <Trash />,
  prompts: <BSChatIcon />,
  preview: <Eye />,
  code: <Code />,
  globe: <Globe />,
  download: <Download />,
  brain: <CpuFill />,
  bookOpen: <JournalText />,
  arena: <Columns />,
  formula: <Calculator />,
  table: <BarChart />, // Approximate
  chart: <BarChart />,
  library: <Images />,
  agentSettings: <Sliders />,
  link: <Link />,
  temperature: <ThermometerHalf />,
  completed: <Check />,
  attachment: <Paperclip />,
  connector: <Plugin />,
  stop: <StopFill />,
  cardList: <CardList />,
  openLink: <BoxArrowUpRight />,
  concurrent: <Shuffle />,
  sequential: <SignpostSplit />,
  groupchat: <PeopleFill />,
  handoff: <ArrowRepeat />,
  toolResult: <UiChecks />,
  trending: <GraphUpArrow />,
  up: <ArrowUp />,
  down: <ArrowDown />,
  resources: <File />,
  eye: <Eye />,
  chatSettings: <Sliders />,
  search: <Search />,
  menu: <List />,
  sources: <Cloud />,
  server: <Server />,
  databaseGear: <DatabaseGear />,
  personalization: <PersonHeart />,
  explainTool: <ChatQuote />,
  mcpServer: <Plug />,
  tool: <Wrench />,
  catalog: <Shop />,
  mail: <Mailbox />,
  panelContract: <ArrowLeft />,
  panelExpand: <ArrowRight />,
  dismiss: <XLg />,
  check: <Check />,
  send: <Send />,
  chevronLeft: <ChevronLeft />,
  chevronRight: <ChevronRight />,
  priority: <ExclamationCircle />,
  chat: <BSChatIcon />,
  settings: <Gear />,
  connect: <UsbPlug />,
  disconnect: <UsbPlugFill />,
  print: <Printer />,
  chevronDown: <ChevronDown />,
  chevronUp: <ChevronUp />,
  logout: <Trash />,
  customize: <Sliders />,
  copyClipboard: <CardList />, // Approximate
};

export const getIcon = (iconName?: IconToken) => {
  if (iconName && iconMap[iconName]) {
    return iconMap[iconName];
  }
  // Fallback handled in render
  return null;
}
