import type { JSX } from "react";
import { IconToken } from "aihappey-types";
import {
  Robot,
  ChatDots,
  ExclamationTriangle,
  Pencil,
  Trash,
  Check,
  Code,
  Globe,
  Download,
  CpuFill,
  JournalText,
  Columns,
  Calculator,
  BarChart,
  Images,
  Link,
  ThermometerHalf,
  Paperclip,
  Plugin,
  StopFill,
  CardList,
  BoxArrowUpRight,
  Shuffle,
  SignpostSplit,
  PeopleFill,
  ArrowRepeat,
  UiChecks,
  GraphUpArrow,
  ArrowUp,
  ArrowDown,
  File,
  Eye,
  Sliders,
  Search,
  List,
  Cloud,
  Server,
  DatabaseGear,
  PersonHeart,
  ChatQuote,
  Plug,
  Wrench,
  Shop,
  Mailbox,
  ArrowLeft,
  ArrowRight,
  XLg,
  Send,
  ChevronLeft,
  ChevronRight,
  ExclamationCircle,
  Chat as BSChatIcon,
  Gear,
  UsbPlug,
  UsbPlugFill,
  Printer,
  Key,
  ChevronDown,
  ChevronUp,
  Plus,
  Camera,
  CameraVideo,
  Palette,
  Mic,
  Speaker,
  Boxes,
  Folder,
  SortDown,
  Hdd,
  BoxArrowUp,
  Broadcast,
  CodeSlash,
  BeakerFill,
  Database,
  Grid3x3Gap,
  Puzzle,
  Window,
  FileText,
  Cash,
  Stars,
  Diagram3,
  Display,
} from "react-bootstrap-icons";
import { Image } from "react-bootstrap";

export const iconMap: Partial<Record<IconToken, JSX.Element>> = {
  robot: <Robot />,
  warning: <ExclamationTriangle />,
  add: <Plus />, // Default fallback or specific mapping
  edit: <Pencil />,
  delete: <Trash />,
  prompts: <BSChatIcon />,
  preview: <Eye />,
  code: <Code />,
  globe: <Globe />,
  download: <Download />,
  brain: <CpuFill />,
  bookOpen: <JournalText />,
  arena: <Columns />,
  transcription: <Mic />,
  transcriptionSettings: <Sliders />,
  imageSettings: <Palette />,
  videoSettings: <Sliders />,
  formula: <Calculator />,
  table: <BarChart />, // Approximate
  chart: <BarChart />,
  images: <Images />,
  videos: <CameraVideo />,
  folder: <Folder />,
  docs: <FileText />,
  console: <Window />,
  agentSettings: <Sliders />,
  link: <Link />,
  speech: <Speaker />,
  speechSettings: <Sliders />,
  temperature: <ThermometerHalf />,
  completed: <Check />,
  attachment: <Paperclip />,
  connector: <Plugin />,
  stop: <StopFill />,
  cardList: <CardList />,
  openLink: <BoxArrowUpRight />,
  concurrent: <Shuffle />,
  sequential: <SignpostSplit />,
  groupchat: <PeopleFill />,
  handoff: <ArrowRepeat />,
  toolResult: <UiChecks />,
  labs: <BeakerFill />,
  trending: <GraphUpArrow />,
  up: <ArrowUp />,
  down: <ArrowDown />,
  resources: <File />,
  webApps: <Grid3x3Gap />,
  components: <Puzzle />,
  storage: <Database />,
  eye: <Eye />,
  chatSettings: <Sliders />,
  search: <Search />,
  menu: <List />,
  skills: <Stars />,
  structuredOutputs: <CodeSlash />,
  sources: <Cloud />,
  server: <Server />,
  databaseGear: <DatabaseGear />,
  personalization: <PersonHeart />,
  contextWindow: <Hdd />,
  realtime: <Broadcast />,
  maxOutputTokens: <BoxArrowUp />,
  language: <ChatDots />,
  explainTool: <ChatQuote />,
  mcpServer: <Plug />,
  tool: <Wrench />,
  catalog: <Shop />,
  mail: <Mailbox />,
  panelContract: <ArrowLeft />,
  endpoint: <Diagram3 />,
  client: <Display />,
  panelExpand: <ArrowRight />,
  dismiss: <XLg />,
  check: <Check />,
  send: <Send />,
  chevronLeft: <ChevronLeft />,
  chevronRight: <ChevronRight />,
  reranking: <SortDown />,
  rerankingSettings: <Sliders />,
  priority: <ExclamationCircle />,
  providers: <Boxes />,
  chat: <BSChatIcon />,
  image: <Image />,
  video: <CameraVideo />,
  settings: <Gear />,
  theme: <Palette />,
  terms: <FileText />,
  privacy: <Key />,
  connect: <UsbPlug />,
  disconnect: <UsbPlugFill />,
  aiImage: <Image />,
  print: <Printer />,
  pricing: <Cash />,
  chevronDown: <ChevronDown />,
  chevronUp: <ChevronUp />,
  logout: <Trash />,
  customize: <Sliders />,
  copyClipboard: <CardList />, // Approximate
};

export const getIcon = (iconName?: IconToken) => {
  if (iconName && iconMap[iconName]) {
    return iconMap[iconName];
  }
  // Fallback handled in render
  return null;
}
