// Generated by scripts/generate-provider-catalog.cjs. Do not edit.
// Metadata source of truth: catalog/index.json and its referenced JSON files.
import type { Provider } from "aihappey-types";
import provider0 from "./catalog/openai.json";
import provider1 from "./catalog/citadelis.json";
import provider2 from "./catalog/zeroentropy.json";
import provider3 from "./catalog/epho.json";
import provider4 from "./catalog/runtype.json";
import provider5 from "./catalog/shadowos.json";
import provider6 from "./catalog/codebase.json";
import provider7 from "./catalog/hcompany.json";
import provider8 from "./catalog/beastlabai.json";
import provider9 from "./catalog/ainvented.json";
import provider10 from "./catalog/plori.json";
import provider11 from "./catalog/connect0.json";
import provider12 from "./catalog/harnessrouter.json";
import provider13 from "./catalog/lelapaai.json";
import provider14 from "./catalog/wafer.json";
import provider15 from "./catalog/nexosai.json";
import provider16 from "./catalog/soniox.json";
import provider17 from "./catalog/notte.json";
import provider18 from "./catalog/orcarouter.json";
import provider19 from "./catalog/appnz.json";
import provider20 from "./catalog/doubleword.json";
import provider21 from "./catalog/routera.json";
import provider22 from "./catalog/mara.json";
import provider23 from "./catalog/mycoai.json";
import provider24 from "./catalog/picklyone.json";
import provider25 from "./catalog/agdev.json";
import provider26 from "./catalog/tembo.json";
import provider27 from "./catalog/poolside.json";
import provider28 from "./catalog/copilot.json";
import provider29 from "./catalog/wiro.json";
import provider30 from "./catalog/tapas.json";
import provider31 from "./catalog/oneinfer.json";
import provider32 from "./catalog/igpt.json";
import provider33 from "./catalog/lara.json";
import provider34 from "./catalog/herma.json";
import provider35 from "./catalog/openadapter.json";
import provider36 from "./catalog/router9.json";
import provider37 from "./catalog/linkup.json";
import provider38 from "./catalog/theoldapi.json";
import provider39 from "./catalog/sapiom.json";
import provider40 from "./catalog/agnesai.json";
import provider41 from "./catalog/augure.json";
import provider42 from "./catalog/sovrgpt.json";
import provider43 from "./catalog/brave.json";
import provider44 from "./catalog/radiance.json";
import provider45 from "./catalog/hetzner.json";
import provider46 from "./catalog/melious.json";
import provider47 from "./catalog/ninjachat.json";
import provider48 from "./catalog/botverse.json";
import provider49 from "./catalog/pixserp.json";
import provider50 from "./catalog/humeai.json";
import provider51 from "./catalog/aiapiworld.json";
import provider52 from "./catalog/concentrate.json";
import provider53 from "./catalog/rebytemodels.json";
import provider54 from "./catalog/rebytetasks.json";
import provider55 from "./catalog/bananapeel.json";
import provider56 from "./catalog/rewindai.json";
import provider57 from "./catalog/moleapi.json";
import provider58 from "./catalog/hostyourai.json";
import provider59 from "./catalog/myrouter.json";
import provider60 from "./catalog/osiris.json";
import provider61 from "./catalog/skypooltoken.json";
import provider62 from "./catalog/luminoai.json";
import provider63 from "./catalog/llmtr.json";
import provider64 from "./catalog/tokenhub.json";
import provider65 from "./catalog/ltx.json";
import provider66 from "./catalog/vibekit.json";
import provider67 from "./catalog/callmissed.json";
import provider68 from "./catalog/freeinference.json";
import provider69 from "./catalog/langbaseagent.json";
import provider70 from "./catalog/langbasepipe.json";
import provider71 from "./catalog/groovedev.json";
import provider72 from "./catalog/monstergaming.json";
import provider73 from "./catalog/apipass.json";
import provider74 from "./catalog/scrapellm.json";
import provider75 from "./catalog/secrypt.json";
import provider76 from "./catalog/merge.json";
import provider77 from "./catalog/virouter.json";
import provider78 from "./catalog/zyloapi.json";
import provider79 from "./catalog/chatqt.json";
import provider80 from "./catalog/opuscode.json";
import provider81 from "./catalog/opengate.json";
import provider82 from "./catalog/pioneer.json";
import provider83 from "./catalog/agen.json";
import provider84 from "./catalog/llama.json";
import provider85 from "./catalog/blink.json";
import provider86 from "./catalog/tierup.json";
import provider87 from "./catalog/llmbase.json";
import provider88 from "./catalog/evidencemd.json";
import provider89 from "./catalog/opencodego.json";
import provider90 from "./catalog/wayscloud.json";
import provider91 from "./catalog/tensorblock.json";
import provider92 from "./catalog/sennoric.json";
import provider93 from "./catalog/commonstack.json";
import provider94 from "./catalog/cheaperinference.json";
import provider95 from "./catalog/paul.json";
import provider96 from "./catalog/ramprouter.json";
import provider97 from "./catalog/hinow.json";
import provider98 from "./catalog/logfare.json";
import provider99 from "./catalog/vikasit.json";
import provider100 from "./catalog/mimicxai.json";
import provider101 from "./catalog/runtimo.json";
import provider102 from "./catalog/wiserouter.json";
import provider103 from "./catalog/tiarina.json";
import provider104 from "./catalog/nodion.json";
import provider105 from "./catalog/maxlayer.json";
import provider106 from "./catalog/manus.json";
import provider107 from "./catalog/critique.json";
import provider108 from "./catalog/darkbloom.json";
import provider109 from "./catalog/scalixworld.json";
import provider110 from "./catalog/meshapi.json";
import provider111 from "./catalog/generalcompute.json";
import provider112 from "./catalog/uncloseai.json";
import provider113 from "./catalog/camelai.json";
import provider114 from "./catalog/m8tes.json";
import provider115 from "./catalog/summa.json";
import provider116 from "./catalog/neuralring.json";
import provider117 from "./catalog/cognitivessai.json";
import provider118 from "./catalog/standardcompute.json";
import provider119 from "./catalog/cursor.json";
import provider120 from "./catalog/skyvern.json";
import provider121 from "./catalog/lumecoder.json";
import provider122 from "./catalog/radient.json";
import provider123 from "./catalog/aihorde.json";
import provider124 from "./catalog/akumi.json";
import provider125 from "./catalog/octagon.json";
import provider126 from "./catalog/aimagicx.json";
import provider127 from "./catalog/impossibl.json";
import provider128 from "./catalog/sluis.json";
import provider129 from "./catalog/sailresearch.json";
import provider130 from "./catalog/hyperbrowser.json";
import provider131 from "./catalog/therouterai.json";
import provider132 from "./catalog/clankie.json";
import provider133 from "./catalog/shannonai.json";
import provider134 from "./catalog/aichixia.json";
import provider135 from "./catalog/nataris.json";
import provider136 from "./catalog/teai.json";
import provider137 from "./catalog/eugpt.json";
import provider138 from "./catalog/fred.json";
import provider139 from "./catalog/anyrouter.json";
import provider140 from "./catalog/geekai.json";
import provider141 from "./catalog/finora.json";
import provider142 from "./catalog/lxg2it.json";
import provider143 from "./catalog/runway.json";
import provider144 from "./catalog/helyxai.json";
import provider145 from "./catalog/mumeai.json";
import provider146 from "./catalog/tinyfish.json";
import provider147 from "./catalog/shengsuanyun.json";
import provider148 from "./catalog/occludra.json";
import provider149 from "./catalog/omniakey.json";
import provider150 from "./catalog/trustedrouter.json";
import provider151 from "./catalog/nouswise.json";
import provider152 from "./catalog/clawhub.json";
import provider153 from "./catalog/orbigpu.json";
import provider154 from "./catalog/ecoia.json";
import provider155 from "./catalog/embercloud.json";
import provider156 from "./catalog/opengateway.json";
import provider157 from "./catalog/holysheepai.json";
import provider158 from "./catalog/lyceum.json";
import provider159 from "./catalog/foureverland.json";
import provider160 from "./catalog/ilmu.json";
import provider161 from "./catalog/select.json";
import provider162 from "./catalog/fivedock.json";
import provider163 from "./catalog/schatziai.json";
import provider164 from "./catalog/fortytwo.json";
import provider165 from "./catalog/simplellm.json";
import provider166 from "./catalog/oraicle.json";
import provider167 from "./catalog/terminalskills.json";
import provider168 from "./catalog/depaza.json";
import provider169 from "./catalog/gptsapi.json";
import provider170 from "./catalog/magisterium.json";
import provider171 from "./catalog/nonkycai.json";
import provider172 from "./catalog/tensorx.json";
import provider173 from "./catalog/embyai.json";
import provider174 from "./catalog/lmrouter.json";
import provider175 from "./catalog/uncensoredchat.json";
import provider176 from "./catalog/selinaai.json";
import provider177 from "./catalog/clauddy.json";
import provider178 from "./catalog/sudorouter.json";
import provider179 from "./catalog/mulerun.json";
import provider180 from "./catalog/baidu.json";
import provider181 from "./catalog/roxy.json";
import provider182 from "./catalog/perceptron.json";
import provider183 from "./catalog/cortex.json";
import provider184 from "./catalog/akashml.json";
import provider185 from "./catalog/morph.json";
import provider186 from "./catalog/streamlake.json";
import provider187 from "./catalog/sovereigneg.json";
import provider188 from "./catalog/runapi.json";
import provider189 from "./catalog/relace.json";
import provider190 from "./catalog/ollama.json";
import provider191 from "./catalog/xiaomimimo.json";
import provider192 from "./catalog/vivgrid.json";
import provider193 from "./catalog/chutes.json";
import provider194 from "./catalog/sunbirdai.json";
import provider195 from "./catalog/miapi.json";
import provider196 from "./catalog/ambient.json";
import provider197 from "./catalog/sandbase.json";
import provider198 from "./catalog/openference.json";
import provider199 from "./catalog/baseapi.json";
import provider200 from "./catalog/preapi.json";
import provider201 from "./catalog/mljunction.json";
import provider202 from "./catalog/addisai.json";
import provider203 from "./catalog/teamday.json";
import provider204 from "./catalog/jassieai.json";
import provider205 from "./catalog/agent37.json";
import provider206 from "./catalog/yutori.json";
import provider207 from "./catalog/cailos.json";
import provider208 from "./catalog/prunaai.json";
import provider209 from "./catalog/imagerouter.json";
import provider210 from "./catalog/gaterouter.json";
import provider211 from "./catalog/ultrasafe.json";
import provider212 from "./catalog/memoryrouter.json";
import provider213 from "./catalog/zebracat.json";
import provider214 from "./catalog/messari.json";
import provider215 from "./catalog/devicai.json";
import provider216 from "./catalog/agentcontainer.json";
import provider217 from "./catalog/interfaze.json";
import provider218 from "./catalog/oodaai.json";
import provider219 from "./catalog/dedaluslabs.json";
import provider220 from "./catalog/stealthgpt.json";
import provider221 from "./catalog/ofoxai.json";
import provider222 from "./catalog/crusoe.json";
import provider223 from "./catalog/routerlink.json";
import provider224 from "./catalog/yollomi.json";
import provider225 from "./catalog/vultr.json";
import provider226 from "./catalog/canrouter.json";
import provider227 from "./catalog/mintrouter.json";
import provider228 from "./catalog/hush.json";
import provider229 from "./catalog/tikhubai.json";
import provider230 from "./catalog/inferlink.json";
import provider231 from "./catalog/knoxchat.json";
import provider232 from "./catalog/tokenspend.json";
import provider233 from "./catalog/auriko.json";
import provider234 from "./catalog/vlmrun.json";
import provider235 from "./catalog/raxai.json";
import provider236 from "./catalog/vogent.json";
import provider237 from "./catalog/aicredits.json";
import provider238 from "./catalog/cheapgrok.json";
import provider239 from "./catalog/railwail.json";
import provider240 from "./catalog/chainhub.json";
import provider241 from "./catalog/zeabur.json";
import provider242 from "./catalog/neuralwatt.json";
import provider243 from "./catalog/pawaai.json";
import provider244 from "./catalog/youcom.json";
import provider245 from "./catalog/aiduet.json";
import provider246 from "./catalog/empiriolabsai.json";
import provider247 from "./catalog/infercom.json";
import provider248 from "./catalog/sargalay.json";
import provider249 from "./catalog/piapi.json";
import provider250 from "./catalog/nagaai.json";
import provider251 from "./catalog/fastrouter.json";
import provider252 from "./catalog/novai.json";
import provider253 from "./catalog/andyapi.json";
import provider254 from "./catalog/onekey.json";
import provider255 from "./catalog/toapis.json";
import provider256 from "./catalog/iapp.json";
import provider257 from "./catalog/blockrun.json";
import provider258 from "./catalog/getgoapi.json";
import provider259 from "./catalog/gonkagate.json";
import provider260 from "./catalog/aki.json";
import provider261 from "./catalog/lilac.json";
import provider262 from "./catalog/kimrel.json";
import provider263 from "./catalog/agentaigateway.json";
import provider264 from "./catalog/lazu.json";
import provider265 from "./catalog/askcodi.json";
import provider266 from "./catalog/martian.json";
import provider267 from "./catalog/huggingface.json";
import provider268 from "./catalog/agentphone.json";
import provider269 from "./catalog/textsynth.json";
import provider270 from "./catalog/keyplex.json";
import provider271 from "./catalog/modelsync.json";
import provider272 from "./catalog/jkaihub.json";
import provider273 from "./catalog/fal.json";
import provider274 from "./catalog/agentics.json";
import provider275 from "./catalog/lumenfall.json";
import provider276 from "./catalog/puter.json";
import provider277 from "./catalog/routeplex.json";
import provider278 from "./catalog/nrpnautilus.json";
import provider279 from "./catalog/bazaarlink.json";
import provider280 from "./catalog/llmkiwi.json";
import provider281 from "./catalog/viablelab.json";
import provider282 from "./catalog/llm7.json";
import provider283 from "./catalog/unbound.json";
import provider284 from "./catalog/airouter.json";
import provider285 from "./catalog/edgee.json";
import provider286 from "./catalog/cline.json";
import provider287 from "./catalog/paxalabs.json";
import provider288 from "./catalog/entrim.json";
import provider289 from "./catalog/shakespeare.json";
import provider290 from "./catalog/ainative.json";
import provider291 from "./catalog/token360.json";
import provider292 from "./catalog/lexico.json";
import provider293 from "./catalog/eagm.json";
import provider294 from "./catalog/setapp.json";
import provider295 from "./catalog/verbatik.json";
import provider296 from "./catalog/aibadgr.json";
import provider297 from "./catalog/webcrawlerapi.json";
import provider298 from "./catalog/shareai.json";
import provider299 from "./catalog/brainiall.json";
import provider300 from "./catalog/surfercloud.json";
import provider301 from "./catalog/openlimits.json";
import provider302 from "./catalog/bastiongpt.json";
import provider303 from "./catalog/arkroute.json";
import provider304 from "./catalog/xpersona.json";
import provider305 from "./catalog/eliza.json";
import provider306 from "./catalog/sovinfra.json";
import provider307 from "./catalog/ionrouter.json";
import provider308 from "./catalog/claudible.json";
import provider309 from "./catalog/llmwise.json";
import provider310 from "./catalog/hanzo.json";
import provider311 from "./catalog/ocrskill.json";
import provider312 from "./catalog/writer.json";
import provider313 from "./catalog/routstr.json";
import provider314 from "./catalog/alphaneural.json";
import provider315 from "./catalog/voiceai.json";
import provider316 from "./catalog/freedomgpt.json";
import provider317 from "./catalog/shuttleai.json";
import provider318 from "./catalog/logicosllmhub.json";
import provider319 from "./catalog/noiz.json";
import provider320 from "./catalog/sufy.json";
import provider321 from "./catalog/mia21.json";
import provider322 from "./catalog/gradium.json";
import provider323 from "./catalog/apiairforce.json";
import provider324 from "./catalog/arliai.json";
import provider325 from "./catalog/rime.json";
import provider326 from "./catalog/kirha.json";
import provider327 from "./catalog/modelrouter.json";
import provider328 from "./catalog/mixedbread.json";
import provider329 from "./catalog/casedev.json";
import provider330 from "./catalog/smartaipi.json";
import provider331 from "./catalog/assisters.json";
import provider332 from "./catalog/apipod.json";
import provider333 from "./catalog/fullai.json";
import provider334 from "./catalog/litai.json";
import provider335 from "./catalog/tokenlab.json";
import provider336 from "./catalog/nexusify.json";
import provider337 from "./catalog/docsrouter.json";
import provider338 from "./catalog/tokenflux.json";
import provider339 from "./catalog/agentsky.json";
import provider340 from "./catalog/ishi.json";
import provider341 from "./catalog/onlypixai.json";
import provider342 from "./catalog/payperq.json";
import provider343 from "./catalog/libertai.json";
import provider344 from "./catalog/jules.json";
import provider345 from "./catalog/antbase.json";
import provider346 from "./catalog/swarms.json";
import provider347 from "./catalog/infron.json";
import provider348 from "./catalog/edenai.json";
import provider349 from "./catalog/maritacaai.json";
import provider350 from "./catalog/dataforseo.json";
import provider351 from "./catalog/cloudferro.json";
import provider352 from "./catalog/jigsawstack.json";
import provider353 from "./catalog/eachlabs.json";
import provider354 from "./catalog/softref.json";
import provider355 from "./catalog/nimbleway.json";
import provider356 from "./catalog/aigateway.json";
import provider357 from "./catalog/llmstats.json";
import provider358 from "./catalog/synthetic.json";
import provider359 from "./catalog/longcat.json";
import provider360 from "./catalog/renderful.json";
import provider361 from "./catalog/apekey.json";
import provider362 from "./catalog/askarc.json";
import provider363 from "./catalog/poe.json";
import provider364 from "./catalog/aisa.json";
import provider365 from "./catalog/everypixellabs.json";
import provider366 from "./catalog/routmy.json";
import provider367 from "./catalog/evolinkai.json";
import provider368 from "./catalog/aibramha.json";
import provider369 from "./catalog/websearchapi.json";
import provider370 from "./catalog/nanogpt.json";
import provider371 from "./catalog/uniapi.json";
import provider372 from "./catalog/parallel.json";
import provider373 from "./catalog/aihubmix.json";
import provider374 from "./catalog/megallm.json";
import provider375 from "./catalog/unrealspeech.json";
import provider376 from "./catalog/tigercity.json";
import provider377 from "./catalog/astica.json";
import provider378 from "./catalog/hicap.json";
import provider379 from "./catalog/modelslab.json";
import provider380 from "./catalog/foundry.json";
import provider381 from "./catalog/zenlayer.json";
import provider382 from "./catalog/thaura.json";
import provider383 from "./catalog/arwriter.json";
import provider384 from "./catalog/quiverai.json";
import provider385 from "./catalog/navyai.json";
import provider386 from "./catalog/apertis.json";
import provider387 from "./catalog/modal.json";
import provider388 from "./catalog/nearai.json";
import provider389 from "./catalog/aiml.json";
import provider390 from "./catalog/smooth.json";
import provider391 from "./catalog/anthropic.json";
import provider392 from "./catalog/heygen.json";
import provider393 from "./catalog/ionet.json";
import provider394 from "./catalog/ellipsis.json";
import provider395 from "./catalog/euqai.json";
import provider396 from "./catalog/glio.json";
import provider397 from "./catalog/orqrouter.json";
import provider398 from "./catalog/carouter.json";
import provider399 from "./catalog/dandolo.json";
import provider400 from "./catalog/literouter.json";
import provider401 from "./catalog/amnt.json";
import provider402 from "./catalog/orqagentruntime.json";
import provider403 from "./catalog/mireye.json";
import provider404 from "./catalog/typecast.json";
import provider405 from "./catalog/founden.json";
import provider406 from "./catalog/vanceai.json";
import provider407 from "./catalog/jiekouai.json";
import provider408 from "./catalog/qiniu.json";
import provider409 from "./catalog/uvoiceai.json";
import provider410 from "./catalog/vapi.json";
import provider411 from "./catalog/waslo.json";
import provider412 from "./catalog/lovo.json";
import provider413 from "./catalog/laozhang.json";
import provider414 from "./catalog/valyu.json";
import provider415 from "./catalog/lunos.json";
import provider416 from "./catalog/fishaudio.json";
import provider417 from "./catalog/netmind.json";
import provider418 from "./catalog/apiyi.json";
import provider419 from "./catalog/zenmux.json";
import provider420 from "./catalog/smallestai.json";
import provider421 from "./catalog/rekaai.json";
import provider422 from "./catalog/aicc.json";
import provider423 from "./catalog/cartesia.json";
import provider424 from "./catalog/yourvoic.json";
import provider425 from "./catalog/google.json";
import provider426 from "./catalog/segmind.json";
import provider427 from "./catalog/mistral.json";
import provider428 from "./catalog/lectoai.json";
import provider429 from "./catalog/gmicloud.json";
import provider430 from "./catalog/byteplus.json";
import provider431 from "./catalog/bytespace.json";
import provider432 from "./catalog/clawlite.json";
import provider433 from "./catalog/cohere.json";
import provider434 from "./catalog/kissapi.json";
import provider435 from "./catalog/groq.json";
import provider436 from "./catalog/spacexai.json";
import provider437 from "./catalog/hyperrouter.json";
import provider438 from "./catalog/together.json";
import provider439 from "./catalog/researchagent.json";
import provider440 from "./catalog/ourtoken.json";
import provider441 from "./catalog/googletranslate.json";
import provider442 from "./catalog/infomaniak.json";
import provider443 from "./catalog/siliconflow.json";
import provider444 from "./catalog/deepbricks.json";
import provider445 from "./catalog/ovhcloud.json";
import provider446 from "./catalog/inworld.json";
import provider447 from "./catalog/cometapi.json";
import provider448 from "./catalog/arklabs.json";
import provider449 from "./catalog/lingvanex.json";
import provider450 from "./catalog/nextbit.json";
import provider451 from "./catalog/cortecs.json";
import provider452 from "./catalog/opperai.json";
import provider453 from "./catalog/eurouter.json";
import provider454 from "./catalog/upstage.json";
import provider455 from "./catalog/deapi.json";
import provider456 from "./catalog/ionos.json";
import provider457 from "./catalog/bergetai.json";
import provider458 from "./catalog/regoloai.json";
import provider459 from "./catalog/pollinations.json";
import provider460 from "./catalog/nlpcloud.json";
import provider461 from "./catalog/hyperstack.json";
import provider462 from "./catalog/requesty.json";
import provider463 from "./catalog/recraft.json";
import provider464 from "./catalog/perplexity.json";
import provider465 from "./catalog/json2video.json";
import provider466 from "./catalog/deepl.json";
import provider467 from "./catalog/speechmatics.json";
import provider468 from "./catalog/gtranslate.json";
import provider469 from "./catalog/gooseai.json";
import provider470 from "./catalog/synexa.json";
import provider471 from "./catalog/moonshot.json";
import provider472 from "./catalog/greenpt.json";
import provider473 from "./catalog/decart.json";
import provider474 from "./catalog/venice.json";
import provider475 from "./catalog/relaxai.json";
import provider476 from "./catalog/horayai.json";
import provider477 from "./catalog/tencenthunyuan.json";
import provider478 from "./catalog/digitalocean.json";
import provider479 from "./catalog/atlascloud.json";
import provider480 from "./catalog/bineric.json";
import provider481 from "./catalog/parasail.json";
import provider482 from "./catalog/asione.json";
import provider483 from "./catalog/sealion.json";
import provider484 from "./catalog/apipie.json";
import provider485 from "./catalog/ideogram.json";
import provider486 from "./catalog/mancerai.json";
import provider487 from "./catalog/stepfun.json";
import provider488 from "./catalog/helicone.json";
import provider489 from "./catalog/jina.json";
import provider490 from "./catalog/amazonbedrock.json";
import provider491 from "./catalog/sunoapi.json";
import provider492 from "./catalog/regraph.json";
import provider493 from "./catalog/nousresearch.json";
import provider494 from "./catalog/bytez.json";
import provider495 from "./catalog/morpheus.json";
import provider496 from "./catalog/matterai.json";
import provider497 from "./catalog/electronhub.json";
import provider498 from "./catalog/ohmygpt.json";
import provider499 from "./catalog/thalam.json";
import provider500 from "./catalog/tavily.json";
import provider501 from "./catalog/opeai.json";
import provider502 from "./catalog/arceeai.json";
import provider503 from "./catalog/daglo.json";
import provider504 from "./catalog/paraloncloud.json";
import provider505 from "./catalog/rodiumai.json";
import provider506 from "./catalog/publicai.json";
import provider507 from "./catalog/miromind.json";
import provider508 from "./catalog/exa.json";
import provider509 from "./catalog/nscale.json";
import provider510 from "./catalog/kilo.json";
import provider511 from "./catalog/featherless.json";
import provider512 from "./catalog/openrouter.json";
import provider513 from "./catalog/cambai.json";
import provider514 from "./catalog/infraxa.json";
import provider515 from "./catalog/openhands.json";
import provider516 from "./catalog/302ai.json";
import provider517 from "./catalog/crazyrouter.json";
import provider518 from "./catalog/agentdiscuss.json";
import provider519 from "./catalog/aether.json";
import provider520 from "./catalog/blackbox.json";
import provider521 from "./catalog/primeintellect.json";
import provider522 from "./catalog/inceptionlabs.json";
import provider523 from "./catalog/commandcode.json";
import provider524 from "./catalog/aionlabs.json";
import provider525 from "./catalog/databricks.json";
import provider526 from "./catalog/inceptron.json";
import provider527 from "./catalog/blackforestlabs.json";
import provider528 from "./catalog/resembleai.json";
import provider529 from "./catalog/abliteration.json";
import provider530 from "./catalog/truefoundry.json";
import provider531 from "./catalog/redpill.json";
import provider532 from "./catalog/browseruse.json";
import provider533 from "./catalog/monica.json";
import provider534 from "./catalog/quantanova.json";
import provider535 from "./catalog/omneity.json";
import provider536 from "./catalog/circuitnotion.json";
import provider537 from "./catalog/lumaai.json";
import provider538 from "./catalog/flatseek.json";
import provider539 from "./catalog/neosantara.json";
import provider540 from "./catalog/meganova.json";
import provider541 from "./catalog/haimaker.json";
import provider542 from "./catalog/supa.json";
import provider543 from "./catalog/llmgateway.json";
import provider544 from "./catalog/assemblyai.json";
import provider545 from "./catalog/mixlayer.json";
import provider546 from "./catalog/gladia.json";
import provider547 from "./catalog/alltoken.json";
import provider548 from "./catalog/clod.json";
import provider549 from "./catalog/wai.json";
import provider550 from "./catalog/opencodezen.json";
import provider551 from "./catalog/chaingpt.json";
import provider552 from "./catalog/azerion.json";
import provider553 from "./catalog/mulerouter.json";
import provider554 from "./catalog/runcrate.json";
import provider555 from "./catalog/modelmax.json";
import provider556 from "./catalog/gptproto.json";
import provider557 from "./catalog/runpod.json";
import provider558 from "./catalog/portkey.json";
import provider559 from "./catalog/routeway.json";
import provider560 from "./catalog/minimax.json";
import provider561 from "./catalog/tetrate.json";
import provider562 from "./catalog/sarvam.json";
import provider563 from "./catalog/deepgram.json";
import provider564 from "./catalog/speechactors.json";
import provider565 from "./catalog/zyphra.json";
import provider566 from "./catalog/nodebyt.json";
import provider567 from "./catalog/pinecone.json";
import provider568 from "./catalog/voyageai.json";
import provider569 from "./catalog/friendli.json";
import provider570 from "./catalog/picsart.json";
import provider571 from "./catalog/lucidquery.json";
import provider572 from "./catalog/bria.json";
import provider573 from "./catalog/murfai.json";
import provider574 from "./catalog/replicate.json";
import provider575 from "./catalog/simplismart.json";
import provider576 from "./catalog/async.json";
import provider577 from "./catalog/azure.json";
import provider578 from "./catalog/deepseek.json";
import provider579 from "./catalog/llmlayer.json";
import provider580 from "./catalog/reve.json";
import provider581 from "./catalog/freepik.json";
import provider582 from "./catalog/ai21.json";
import provider583 from "./catalog/avian.json";
import provider584 from "./catalog/cloudrift.json";
import provider585 from "./catalog/baseten.json";
import provider586 from "./catalog/echo.json";
import provider587 from "./catalog/tinfoil.json";
import provider588 from "./catalog/llmapi.json";
import provider589 from "./catalog/nebius.json";
import provider590 from "./catalog/audixa.json";
import provider591 from "./catalog/klingai.json";
import provider592 from "./catalog/vidu.json";
import provider593 from "./catalog/deepinfra.json";
import provider594 from "./catalog/nvidia.json";
import provider595 from "./catalog/runware.json";
import provider596 from "./catalog/cencori.json";
import provider597 from "./catalog/canopywave.json";
import provider598 from "./catalog/alibaba.json";
import provider599 from "./catalog/cirrascale.json";
import provider600 from "./catalog/aivara.json";
import provider601 from "./catalog/inferencenet.json";
import provider602 from "./catalog/condensechat.json";
import provider603 from "./catalog/fikra.json";
import provider604 from "./catalog/telnyx.json";
import provider605 from "./catalog/stabilityai.json";
import provider606 from "./catalog/novita.json";
import provider607 from "./catalog/speechify.json";
import provider608 from "./catalog/scaleway.json";
import provider609 from "./catalog/sambanova.json";
import provider610 from "./catalog/ttsreader.json";
import provider611 from "./catalog/samtal.json";
import provider612 from "./catalog/verda.json";
import provider613 from "./catalog/fireworks.json";
import provider614 from "./catalog/cerebras.json";
import provider615 from "./catalog/zai.json";
import provider616 from "./catalog/hyperbolic.json";
import provider617 from "./catalog/elevenlabs.json";

export const PROVIDER_CATALOG = {
  "openai": provider0,
  "citadelis": provider1,
  "zeroentropy": provider2,
  "epho": provider3,
  "runtype": provider4,
  "shadowos": provider5,
  "codebase": provider6,
  "hcompany": provider7,
  "beastlabai": provider8,
  "ainvented": provider9,
  "plori": provider10,
  "connect0": provider11,
  "harnessrouter": provider12,
  "lelapaai": provider13,
  "wafer": provider14,
  "nexosai": provider15,
  "soniox": provider16,
  "notte": provider17,
  "orcarouter": provider18,
  "appnz": provider19,
  "doubleword": provider20,
  "routera": provider21,
  "mara": provider22,
  "mycoai": provider23,
  "picklyone": provider24,
  "agdev": provider25,
  "tembo": provider26,
  "poolside": provider27,
  "copilot": provider28,
  "wiro": provider29,
  "tapas": provider30,
  "oneinfer": provider31,
  "igpt": provider32,
  "lara": provider33,
  "herma": provider34,
  "openadapter": provider35,
  "router9": provider36,
  "linkup": provider37,
  "theoldapi": provider38,
  "sapiom": provider39,
  "agnesai": provider40,
  "augure": provider41,
  "sovrgpt": provider42,
  "brave": provider43,
  "radiance": provider44,
  "hetzner": provider45,
  "melious": provider46,
  "ninjachat": provider47,
  "botverse": provider48,
  "pixserp": provider49,
  "humeai": provider50,
  "aiapiworld": provider51,
  "concentrate": provider52,
  "rebytemodels": provider53,
  "rebytetasks": provider54,
  "bananapeel": provider55,
  "rewindai": provider56,
  "moleapi": provider57,
  "hostyourai": provider58,
  "myrouter": provider59,
  "osiris": provider60,
  "skypooltoken": provider61,
  "luminoai": provider62,
  "llmtr": provider63,
  "tokenhub": provider64,
  "ltx": provider65,
  "vibekit": provider66,
  "callmissed": provider67,
  "freeinference": provider68,
  "langbaseagent": provider69,
  "langbasepipe": provider70,
  "groovedev": provider71,
  "monstergaming": provider72,
  "apipass": provider73,
  "scrapellm": provider74,
  "secrypt": provider75,
  "merge": provider76,
  "virouter": provider77,
  "zyloapi": provider78,
  "chatqt": provider79,
  "opuscode": provider80,
  "opengate": provider81,
  "pioneer": provider82,
  "agen": provider83,
  "llama": provider84,
  "blink": provider85,
  "tierup": provider86,
  "llmbase": provider87,
  "evidencemd": provider88,
  "opencodego": provider89,
  "wayscloud": provider90,
  "tensorblock": provider91,
  "sennoric": provider92,
  "commonstack": provider93,
  "cheaperinference": provider94,
  "paul": provider95,
  "ramprouter": provider96,
  "hinow": provider97,
  "logfare": provider98,
  "vikasit": provider99,
  "mimicxai": provider100,
  "runtimo": provider101,
  "wiserouter": provider102,
  "tiarina": provider103,
  "nodion": provider104,
  "maxlayer": provider105,
  "manus": provider106,
  "critique": provider107,
  "darkbloom": provider108,
  "scalixworld": provider109,
  "meshapi": provider110,
  "generalcompute": provider111,
  "uncloseai": provider112,
  "camelai": provider113,
  "m8tes": provider114,
  "summa": provider115,
  "neuralring": provider116,
  "cognitivessai": provider117,
  "standardcompute": provider118,
  "cursor": provider119,
  "skyvern": provider120,
  "lumecoder": provider121,
  "radient": provider122,
  "aihorde": provider123,
  "akumi": provider124,
  "octagon": provider125,
  "aimagicx": provider126,
  "impossibl": provider127,
  "sluis": provider128,
  "sailresearch": provider129,
  "hyperbrowser": provider130,
  "therouterai": provider131,
  "clankie": provider132,
  "shannonai": provider133,
  "aichixia": provider134,
  "nataris": provider135,
  "teai": provider136,
  "eugpt": provider137,
  "fred": provider138,
  "anyrouter": provider139,
  "geekai": provider140,
  "finora": provider141,
  "lxg2it": provider142,
  "runway": provider143,
  "helyxai": provider144,
  "mumeai": provider145,
  "tinyfish": provider146,
  "shengsuanyun": provider147,
  "occludra": provider148,
  "omniakey": provider149,
  "trustedrouter": provider150,
  "nouswise": provider151,
  "clawhub": provider152,
  "orbigpu": provider153,
  "ecoia": provider154,
  "embercloud": provider155,
  "opengateway": provider156,
  "holysheepai": provider157,
  "lyceum": provider158,
  "foureverland": provider159,
  "ilmu": provider160,
  "select": provider161,
  "fivedock": provider162,
  "schatziai": provider163,
  "fortytwo": provider164,
  "simplellm": provider165,
  "oraicle": provider166,
  "terminalskills": provider167,
  "depaza": provider168,
  "gptsapi": provider169,
  "magisterium": provider170,
  "nonkycai": provider171,
  "tensorx": provider172,
  "embyai": provider173,
  "lmrouter": provider174,
  "uncensoredchat": provider175,
  "selinaai": provider176,
  "clauddy": provider177,
  "sudorouter": provider178,
  "mulerun": provider179,
  "baidu": provider180,
  "roxy": provider181,
  "perceptron": provider182,
  "cortex": provider183,
  "akashml": provider184,
  "morph": provider185,
  "streamlake": provider186,
  "sovereigneg": provider187,
  "runapi": provider188,
  "relace": provider189,
  "ollama": provider190,
  "xiaomimimo": provider191,
  "vivgrid": provider192,
  "chutes": provider193,
  "sunbirdai": provider194,
  "miapi": provider195,
  "ambient": provider196,
  "sandbase": provider197,
  "openference": provider198,
  "baseapi": provider199,
  "preapi": provider200,
  "mljunction": provider201,
  "addisai": provider202,
  "teamday": provider203,
  "jassieai": provider204,
  "agent37": provider205,
  "yutori": provider206,
  "cailos": provider207,
  "prunaai": provider208,
  "imagerouter": provider209,
  "gaterouter": provider210,
  "ultrasafe": provider211,
  "memoryrouter": provider212,
  "zebracat": provider213,
  "messari": provider214,
  "devicai": provider215,
  "agentcontainer": provider216,
  "interfaze": provider217,
  "oodaai": provider218,
  "dedaluslabs": provider219,
  "stealthgpt": provider220,
  "ofoxai": provider221,
  "crusoe": provider222,
  "routerlink": provider223,
  "yollomi": provider224,
  "vultr": provider225,
  "canrouter": provider226,
  "mintrouter": provider227,
  "hush": provider228,
  "tikhubai": provider229,
  "inferlink": provider230,
  "knoxchat": provider231,
  "tokenspend": provider232,
  "auriko": provider233,
  "vlmrun": provider234,
  "raxai": provider235,
  "vogent": provider236,
  "aicredits": provider237,
  "cheapgrok": provider238,
  "railwail": provider239,
  "chainhub": provider240,
  "zeabur": provider241,
  "neuralwatt": provider242,
  "pawaai": provider243,
  "youcom": provider244,
  "aiduet": provider245,
  "empiriolabsai": provider246,
  "infercom": provider247,
  "sargalay": provider248,
  "piapi": provider249,
  "nagaai": provider250,
  "fastrouter": provider251,
  "novai": provider252,
  "andyapi": provider253,
  "onekey": provider254,
  "toapis": provider255,
  "iapp": provider256,
  "blockrun": provider257,
  "getgoapi": provider258,
  "gonkagate": provider259,
  "aki": provider260,
  "lilac": provider261,
  "kimrel": provider262,
  "agentaigateway": provider263,
  "lazu": provider264,
  "askcodi": provider265,
  "martian": provider266,
  "huggingface": provider267,
  "agentphone": provider268,
  "textsynth": provider269,
  "keyplex": provider270,
  "modelsync": provider271,
  "jkaihub": provider272,
  "fal": provider273,
  "agentics": provider274,
  "lumenfall": provider275,
  "puter": provider276,
  "routeplex": provider277,
  "nrpnautilus": provider278,
  "bazaarlink": provider279,
  "llmkiwi": provider280,
  "viablelab": provider281,
  "llm7": provider282,
  "unbound": provider283,
  "airouter": provider284,
  "edgee": provider285,
  "cline": provider286,
  "paxalabs": provider287,
  "entrim": provider288,
  "shakespeare": provider289,
  "ainative": provider290,
  "token360": provider291,
  "lexico": provider292,
  "eagm": provider293,
  "setapp": provider294,
  "verbatik": provider295,
  "aibadgr": provider296,
  "webcrawlerapi": provider297,
  "shareai": provider298,
  "brainiall": provider299,
  "surfercloud": provider300,
  "openlimits": provider301,
  "bastiongpt": provider302,
  "arkroute": provider303,
  "xpersona": provider304,
  "eliza": provider305,
  "sovinfra": provider306,
  "ionrouter": provider307,
  "claudible": provider308,
  "llmwise": provider309,
  "hanzo": provider310,
  "ocrskill": provider311,
  "writer": provider312,
  "routstr": provider313,
  "alphaneural": provider314,
  "voiceai": provider315,
  "freedomgpt": provider316,
  "shuttleai": provider317,
  "logicosllmhub": provider318,
  "noiz": provider319,
  "sufy": provider320,
  "mia21": provider321,
  "gradium": provider322,
  "apiairforce": provider323,
  "arliai": provider324,
  "rime": provider325,
  "kirha": provider326,
  "modelrouter": provider327,
  "mixedbread": provider328,
  "casedev": provider329,
  "smartaipi": provider330,
  "assisters": provider331,
  "apipod": provider332,
  "fullai": provider333,
  "litai": provider334,
  "tokenlab": provider335,
  "nexusify": provider336,
  "docsrouter": provider337,
  "tokenflux": provider338,
  "agentsky": provider339,
  "ishi": provider340,
  "onlypixai": provider341,
  "payperq": provider342,
  "libertai": provider343,
  "jules": provider344,
  "antbase": provider345,
  "swarms": provider346,
  "infron": provider347,
  "edenai": provider348,
  "maritacaai": provider349,
  "dataforseo": provider350,
  "cloudferro": provider351,
  "jigsawstack": provider352,
  "eachlabs": provider353,
  "softref": provider354,
  "nimbleway": provider355,
  "aigateway": provider356,
  "llmstats": provider357,
  "synthetic": provider358,
  "longcat": provider359,
  "renderful": provider360,
  "apekey": provider361,
  "askarc": provider362,
  "poe": provider363,
  "aisa": provider364,
  "everypixellabs": provider365,
  "routmy": provider366,
  "evolinkai": provider367,
  "aibramha": provider368,
  "websearchapi": provider369,
  "nanogpt": provider370,
  "uniapi": provider371,
  "parallel": provider372,
  "aihubmix": provider373,
  "megallm": provider374,
  "unrealspeech": provider375,
  "tigercity": provider376,
  "astica": provider377,
  "hicap": provider378,
  "modelslab": provider379,
  "foundry": provider380,
  "zenlayer": provider381,
  "thaura": provider382,
  "arwriter": provider383,
  "quiverai": provider384,
  "navyai": provider385,
  "apertis": provider386,
  "modal": provider387,
  "nearai": provider388,
  "aiml": provider389,
  "smooth": provider390,
  "anthropic": provider391,
  "heygen": provider392,
  "ionet": provider393,
  "ellipsis": provider394,
  "euqai": provider395,
  "glio": provider396,
  "orqrouter": provider397,
  "carouter": provider398,
  "dandolo": provider399,
  "literouter": provider400,
  "amnt": provider401,
  "orqagentruntime": provider402,
  "mireye": provider403,
  "typecast": provider404,
  "founden": provider405,
  "vanceai": provider406,
  "jiekouai": provider407,
  "qiniu": provider408,
  "uvoiceai": provider409,
  "vapi": provider410,
  "waslo": provider411,
  "lovo": provider412,
  "laozhang": provider413,
  "valyu": provider414,
  "lunos": provider415,
  "fishaudio": provider416,
  "netmind": provider417,
  "apiyi": provider418,
  "zenmux": provider419,
  "smallestai": provider420,
  "rekaai": provider421,
  "aicc": provider422,
  "cartesia": provider423,
  "yourvoic": provider424,
  "google": provider425,
  "segmind": provider426,
  "mistral": provider427,
  "lectoai": provider428,
  "gmicloud": provider429,
  "byteplus": provider430,
  "bytespace": provider431,
  "clawlite": provider432,
  "cohere": provider433,
  "kissapi": provider434,
  "groq": provider435,
  "spacexai": provider436,
  "hyperrouter": provider437,
  "together": provider438,
  "researchagent": provider439,
  "ourtoken": provider440,
  "googletranslate": provider441,
  "infomaniak": provider442,
  "siliconflow": provider443,
  "deepbricks": provider444,
  "ovhcloud": provider445,
  "inworld": provider446,
  "cometapi": provider447,
  "arklabs": provider448,
  "lingvanex": provider449,
  "nextbit": provider450,
  "cortecs": provider451,
  "opperai": provider452,
  "eurouter": provider453,
  "upstage": provider454,
  "deapi": provider455,
  "ionos": provider456,
  "bergetai": provider457,
  "regoloai": provider458,
  "pollinations": provider459,
  "nlpcloud": provider460,
  "hyperstack": provider461,
  "requesty": provider462,
  "recraft": provider463,
  "perplexity": provider464,
  "json2video": provider465,
  "deepl": provider466,
  "speechmatics": provider467,
  "gtranslate": provider468,
  "gooseai": provider469,
  "synexa": provider470,
  "moonshot": provider471,
  "greenpt": provider472,
  "decart": provider473,
  "venice": provider474,
  "relaxai": provider475,
  "horayai": provider476,
  "tencenthunyuan": provider477,
  "digitalocean": provider478,
  "atlascloud": provider479,
  "bineric": provider480,
  "parasail": provider481,
  "asione": provider482,
  "sealion": provider483,
  "apipie": provider484,
  "ideogram": provider485,
  "mancerai": provider486,
  "stepfun": provider487,
  "helicone": provider488,
  "jina": provider489,
  "amazonbedrock": provider490,
  "sunoapi": provider491,
  "regraph": provider492,
  "nousresearch": provider493,
  "bytez": provider494,
  "morpheus": provider495,
  "matterai": provider496,
  "electronhub": provider497,
  "ohmygpt": provider498,
  "thalam": provider499,
  "tavily": provider500,
  "opeai": provider501,
  "arceeai": provider502,
  "daglo": provider503,
  "paraloncloud": provider504,
  "rodiumai": provider505,
  "publicai": provider506,
  "miromind": provider507,
  "exa": provider508,
  "nscale": provider509,
  "kilo": provider510,
  "featherless": provider511,
  "openrouter": provider512,
  "cambai": provider513,
  "infraxa": provider514,
  "openhands": provider515,
  "ai302": provider516,
  "crazyrouter": provider517,
  "agentdiscuss": provider518,
  "aether": provider519,
  "blackbox": provider520,
  "primeintellect": provider521,
  "inceptionlabs": provider522,
  "commandcode": provider523,
  "aionlabs": provider524,
  "databricks": provider525,
  "inceptron": provider526,
  "blackforestlabs": provider527,
  "resembleai": provider528,
  "abliteration": provider529,
  "truefoundry": provider530,
  "redpill": provider531,
  "browseruse": provider532,
  "monica": provider533,
  "quantanova": provider534,
  "omneity": provider535,
  "circuitnotion": provider536,
  "lumaai": provider537,
  "flatseek": provider538,
  "neosantara": provider539,
  "meganova": provider540,
  "haimaker": provider541,
  "supa": provider542,
  "llmgateway": provider543,
  "assemblyai": provider544,
  "mixlayer": provider545,
  "gladia": provider546,
  "alltoken": provider547,
  "clod": provider548,
  "wai": provider549,
  "opencodezen": provider550,
  "chaingpt": provider551,
  "azerion": provider552,
  "mulerouter": provider553,
  "runcrate": provider554,
  "modelmax": provider555,
  "gptproto": provider556,
  "runpod": provider557,
  "portkey": provider558,
  "routeway": provider559,
  "minimax": provider560,
  "tetrate": provider561,
  "sarvam": provider562,
  "deepgram": provider563,
  "speechactors": provider564,
  "zyphra": provider565,
  "nodebyt": provider566,
  "pinecone": provider567,
  "voyageai": provider568,
  "friendli": provider569,
  "picsart": provider570,
  "lucidquery": provider571,
  "bria": provider572,
  "murfai": provider573,
  "replicate": provider574,
  "simplismart": provider575,
  "async": provider576,
  "azure": provider577,
  "deepseek": provider578,
  "llmlayer": provider579,
  "reve": provider580,
  "freepik": provider581,
  "ai21": provider582,
  "avian": provider583,
  "cloudrift": provider584,
  "baseten": provider585,
  "echo": provider586,
  "tinfoil": provider587,
  "llmapi": provider588,
  "nebius": provider589,
  "audixa": provider590,
  "klingai": provider591,
  "vidu": provider592,
  "deepinfra": provider593,
  "nvidia": provider594,
  "runware": provider595,
  "cencori": provider596,
  "canopywave": provider597,
  "alibaba": provider598,
  "cirrascale": provider599,
  "aivara": provider600,
  "inferencenet": provider601,
  "condensechat": provider602,
  "fikra": provider603,
  "telnyx": provider604,
  "stabilityai": provider605,
  "novita": provider606,
  "speechify": provider607,
  "scaleway": provider608,
  "sambanova": provider609,
  "ttsreader": provider610,
  "samtal": provider611,
  "verda": provider612,
  "fireworks": provider613,
  "cerebras": provider614,
  "zai": provider615,
  "hyperbolic": provider616,
  "elevenlabs": provider617,
} as Record<string, Omit<Provider, "createGatewayMetadata">>;
