import * as React from "react";
import type { ComponentProps, JSX } from "react";
import { Button as FluentButton, Hamburger, Tooltip } from "@fluentui/react-components";
import type { IconToken } from "aihappey-types";
import {
  AddRegular,
  EditRegular,
  DeleteRegular,
  SendRegular,
  SettingsRegular,
  ChevronDownRegular,
  ChevronUpRegular,
  PromptRegular,
  BotFilled,
  DoorArrowRightRegular,
  PeopleSettingsRegular,
  PersonHeartRegular,
  DatabasePersonRegular,
  AttachRegular,
  LinkRegular,
  OpenRegular,
  ConnectorRegular,
  CopyRegular,
  EyeRegular,
  StopFilled,
  DocumentTextToolboxRegular,
  BookOpenRegular,
  GlobeRegular,
  ImageStackRegular,
  BrainRegular,
  UsbPlugFilled,
  CheckmarkRegular,
  CodeRegular,
  ChartMultipleRegular,
  TableRegular,
  MathFormulaRegular,
  ArrowDownloadRegular,
  PrintRegular,
  PlugConnectedAddRegular,
  PlugConnectedCheckmarkRegular,
  DualScreenGroupRegular,
  SlideTextSparkleRegular,
  TemperatureRegular,
  ArrowTrendingRegular,
  ListRegular,
  ChatSettingsRegular,
  WarningRegular,
  ServerRegular,
  SearchRegular,
  PanelRightContractRegular,
  PanelRightExpandRegular,
  MailRegular,
  SettingsChatRegular,
  ArrowSplitRegular,
  ArrowRoutingRegular,
  PeopleChatRegular,
  PeopleSwapRegular,
  ArrowUpRegular,
  ArrowDownRegular,
  BuildingShopRegular,
  ChatRegular,
  DismissRegular,
  ImportantFilled,
  WrenchRegular,
  ChevronRightRegular,
  ChevronLeftRegular,
  CloudLinkRegular,
  ImageSparkleRegular,
  ImageRegular,
  ColorRegular,
  ContentSettingsRegular,
  MicSettingsRegular,
  MicRegular,
  SpeakerSettingsRegular,
  SpeakerBoxRegular,
  PlugConnectedRegular,
  FolderRegular,
  DocumentLinkRegular,
  ArrowSortDownRegular,
  ArrowSortDownLinesRegular,
  TextBulletListSquareSettingsRegular,
  DatabaseRegular,
  ArrowExportRegular,
  LiveRegular,
  CodeBlockRegular,
  BeakerRegular,
  DatabaseWindowRegular,
  AppsRegular,
  VideoRegular,
  PuzzlePieceRegular,
  VideoSettingsRegular,
  TextTRegular,
  WindowRegular,
  DocumentRegular,
  KeyRegular,
  ShieldCheckmarkRegular,
  ShieldLockRegular,
  WindowSettingsRegular,
  DocumentTextRegular,
  PaymentRegular,
  MoneyRegular,
  WalletRegular,
  CurrencyDollarEuroRegular,
  SparkleRegular,
  ChannelRegular,
  DatabaseSearchRegular,
  WindowWrenchRegular,
  CloudCubeRegular,
  BrainCircuitRegular,
  RouterRegular,
} from "@fluentui/react-icons";

export const iconMap: Record<IconToken, React.ComponentType<any>> = {
  add: AddRegular,
  edit: EditRegular,
  delete: DeleteRegular,
  prompts: PromptRegular,
  resources: DocumentLinkRegular,
  mcpServer: UsbPlugFilled,
  send: SendRegular,
  connect: PlugConnectedAddRegular,
  speech: SpeakerBoxRegular,
  speechSettings: SpeakerSettingsRegular,
  transcription: MicRegular,
  transcriptionSettings: MicSettingsRegular,
  imageSettings: ContentSettingsRegular,
  videoSettings: VideoSettingsRegular,
  disconnect: PlugConnectedCheckmarkRegular,
  images: ImageStackRegular,
  videos: VideoRegular,
  folder: FolderRegular,
  server: ServerRegular,
  endpoint: ChannelRegular,
  client: WindowRegular,
  connector: ConnectorRegular,
  tool: WrenchRegular,
  print: PrintRegular,
  openLink: OpenRegular,
  gateway_router: RouterRegular,
  model_provider: BrainCircuitRegular,
  app_tools: WindowWrenchRegular,
  search_data: DatabaseSearchRegular,
  media_voice: OpenRegular,
  inference_compute: CloudCubeRegular,
  robot: BotFilled,
  chatSettings: ChatSettingsRegular,
  arena: DualScreenGroupRegular,
  download: ArrowDownloadRegular,
  formula: MathFormulaRegular,
  table: TableRegular,
  labs: BeakerRegular,
  mail: MailRegular,
  theme: ColorRegular,
  warning: WarningRegular,
  storage: DatabaseRegular,
  search: SearchRegular,
  chat: ChatRegular,
  panelContract: PanelRightContractRegular,
  panelExpand: PanelRightExpandRegular,
  chart: ChartMultipleRegular,
  webApps: AppsRegular,
  components: PuzzlePieceRegular,
  globe: GlobeRegular,
  check: CheckmarkRegular,
  code: CodeRegular,
  temperature: TemperatureRegular,
  brain: BrainRegular,
  bookOpen: BookOpenRegular,
  trending: ArrowTrendingRegular,
  link: LinkRegular,
  cardList: ListRegular,
  explainTool: SlideTextSparkleRegular,
  preview: EyeRegular,
  toolResult: DocumentTextToolboxRegular,
  stop: StopFilled,
  reranking: ArrowSortDownLinesRegular,
  rerankingSettings: TextBulletListSquareSettingsRegular,
  menu: Hamburger,
  attachment: AttachRegular,
  concurrent: ArrowSplitRegular,
  realtime: LiveRegular,
  realtimeSettings: SettingsRegular,
  providers: PlugConnectedRegular,
  sequential: ArrowRoutingRegular,
  aiImage: ImageSparkleRegular,
  language: TextTRegular,
  groupchat: PeopleChatRegular,
  handoff: PeopleSwapRegular,
  catalog: BuildingShopRegular,
  completed: CheckmarkRegular,
  up: ArrowUpRegular,
  priority: ImportantFilled,
  down: ArrowDownRegular,
  dismiss: DismissRegular,
  agentSettings: SettingsChatRegular,
  eye: EyeRegular,
  image: ImageRegular,
  video: VideoRegular,
  skills: SparkleRegular,
  databaseGear: DatabasePersonRegular,
  personalization: PersonHeartRegular,
  contextWindow: DatabaseWindowRegular,
  structuredOutputs: CodeBlockRegular,
  maxOutputTokens: ArrowExportRegular,
  customize: PeopleSettingsRegular,
  logout: DoorArrowRightRegular,
  copyClipboard: CopyRegular,
  settings: SettingsRegular,
  docs: BookOpenRegular,
  pricing: CurrencyDollarEuroRegular,
  terms: DocumentTextRegular,
  privacy: ShieldLockRegular,
  console: WindowSettingsRegular,
  sources: CloudLinkRegular,
  chevronDown: ChevronDownRegular,
  chevronUp: ChevronUpRegular,
  chevronLeft: ChevronLeftRegular,
  chevronRight: ChevronRightRegular,
};

export const Button = ({
  variant = "primary",
  size = "medium",
  icon,
  iconPosition = "left",
  title,
  children,
  ...rest
}: ComponentProps<"button"> & {
  variant?: string;
  size?: string;
  title?: string;
  icon?: IconToken;
  iconPosition?: "left" | "right";
  children?: React.ReactNode;
}): JSX.Element => {
  const IconElem = icon ? iconMap[icon] : undefined;

  const appearance = variant === "primary"
    ? "primary"
    : variant === "secondary"
      ? "secondary"
      : variant === "outline"
        ? "outline"
        : "transparent";

  const sizeValue = size === "sm" || size === "small"
    ? "small"
    : size === "lg" || size === "large"
      ? "large"
      : "medium";

  const button = <FluentButton
    appearance={appearance}
    size={sizeValue}
    icon={IconElem && iconPosition === "left" ? <IconElem /> : undefined}
    iconAfter={
      IconElem && iconPosition === "right" ? <IconElem /> : undefined
    }
    {...(rest as any)}
  >
    {children}
  </FluentButton>;

  return title ? <Tooltip relationship="label" content={title}>
    {button}
  </Tooltip> : button;
};
